<a href="https://colab.research.google.com/github/tran0467/User-behaviour-analysis/blob/main/Data_analysis_(Categorial).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:

from scipy.stats import kendalltau, pearsonr, spearmanr
import pandas as pd
import numpy as np
from scipy import stats
import seaborn as sns                       #visualisation
import matplotlib.pyplot as plt             #visualisation
from sklearn.linear_model import LinearRegression
%matplotlib inline     
sns.set(color_codes=True)
%load_ext google.colab.data_table

def kendall_pval(x,y):
  return kendalltau(x,y)[1]
    
def pearsonr_pval(x,y):
  return pearsonr(x,y)[1]
    
def spearmanr_pval(x,y):
  return spearmanr(x,y)[1]

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# Enable multiple cell outputs
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

The google.colab.data_table extension is already loaded. To reload it, use:
  %reload_ext google.colab.data_table

In [ ]:
# First-Second value features against First Value Health Profile
pathGeneral = "/content/drive/MyDrive/05. STUDY/FLINDERS/2020-08 Masters Thesis/General_Feature_with_Spent_Time.csv"
dfGeneral = pd.read_csv(pathGeneral)
pathDiffFirstSecond = "/content/drive/MyDrive/05. STUDY/FLINDERS/2020-08 Masters Thesis/Diff_Direction_first_second_value.csv"
dfDiffFirstSecond = pd.read_csv(pathDiffFirstSecond)
pathDiffFirstLast = "/content/drive/MyDrive/05. STUDY/FLINDERS/2020-08 Masters Thesis/Diff_Direction_first_last_value.csv"
dfDiffFirstLast = pd.read_csv(pathDiffFirstLast)

pathProfileFirst = "/content/drive/MyDrive/05. STUDY/FLINDERS/2020-08 Masters Thesis/dfHealthProfile_FirstValue.csv"
dfProfileFirst = pd.read_csv(pathProfileFirst)
pathProfileLast = "/content/drive/MyDrive/05. STUDY/FLINDERS/2020-08 Masters Thesis/dfHealthProfile_LastValue.csv"
dfProfileLast = pd.read_csv(pathProfileLast)

In [ ]:
dfDiffFirstSecond2 = dfDiffFirstSecond[['Visitor_ID','Age Direction',	'Height Direction',	'Weight Direction',
                                        'Smoking Direction',	'Alcohol Direction',	'Conceive Direction', 'Month Direction',
                                        'Children Direction',	'STI Direction',	'STI Positive Direction',	
                                        'Menstrual_Information Direction', 'Sex_Frequency Direction', 'Sex_Right_Time Direction',
                                        'Contraception Direction']].copy()
dfDiffFirstSecond2 = dfDiffFirstSecond2.replace([1,0.5],"Positive")
dfDiffFirstSecond2 = dfDiffFirstSecond2.replace([-1,-0.5],"Negative")
dfDiffFirstSecond2 = dfDiffFirstSecond2.replace(0,"No change")

dfDiffFirstLast2 = dfDiffFirstLast[['Visitor_ID','Age Direction',	'Height Direction',	'Weight Direction',
                                        'Smoking Direction',	'Alcohol Direction',	'Conceive Direction', 'Month Direction',
                                        'Children Direction',	'STI Direction',	'STI Positive Direction',	
                                        'Menstrual_Information Direction', 'Sex_Frequency Direction', 'Sex_Right_Time Direction',
                                        'Contraception Direction']].copy()
dfDiffFirstLast2 = dfDiffFirstLast2.replace([1,0.5],"Positive")
dfDiffFirstLast2 = dfDiffFirstLast2.replace([-1,-0.5],"Negative")
dfDiffFirstLast2 = dfDiffFirstLast2.replace(0,"No change")

dfProfileFirst2 = dfProfileFirst[['Visitor_ID','Gender','Trying_Conceive', 'Previous_Children','STI_Tested','STI_Positive','Menstrual_Information',
                                  'Sex_Right_Time','Contraception']].copy()
dfProfileLast2 = dfProfileLast[['Visitor_ID','Gender','Trying_Conceive', 'Previous_Children','STI_Tested','STI_Positive','Menstrual_Information',
                                  'Sex_Right_Time','Contraception']].copy()

dfProfileFirst_DiffSecond = dfProfileFirst2.merge(dfDiffFirstSecond2, on = 'Visitor_ID', how = 'left')
dfProfileFirst_DiffLast = dfProfileFirst2.merge(dfDiffFirstLast2, on = 'Visitor_ID', how = 'left')
dfProfileLast_DiffSecond = dfProfileLast2.merge(dfDiffFirstSecond2, on = 'Visitor_ID', how = 'left')
dfProfileLast_DiffLast = dfProfileLast2.merge(dfDiffFirstLast2, on = 'Visitor_ID', how = 'left')
dfProfileLast_DiffLast

            Visitor_ID Gender  ... Sex_Right_Time Direction Contraception Direction
0     00052d764372f8e1    Men  ...                      NaN                     NaN
1     0010038311a193ca  Women  ...                      NaN               No change
2     001ad62ea7bffe81  Women  ...                      NaN                     NaN
3     001f49b0bfe37865  Women  ...                No change               No change
4     00274a3448b59cbd  Women  ...                No change               No change
...                ...    ...  ...                      ...                     ...
4125  ffbbfa8e0095fa45  Women  ...                No change               No change
4126  ffc980a4b6d372c6  Women  ...                No change               No change
4127  ffcf6cfd8c6aac98  Women  ...                      NaN                     NaN
4128  ffd1a676c10e1bcf  Women  ...                 Negative                Negative
4129  ffd318dc96254aab  Women  ...                No change               No change

[4130 rows x 23 columns]

In [ ]:
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Age Direction'],dfProfileFirst_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

In [ ]:
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Height Direction'],dfProfileFirst_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Weight Direction'],dfProfileFirst_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Smoking Direction'],dfProfileFirst_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Alcohol Direction'],dfProfileFirst_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Conceive Direction'],dfProfileFirst_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Month Direction'],dfProfileFirst_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Children Direction'],dfProfileFirst_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Direction'],dfProfileFirst_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Positive Direction'],dfProfileFirst_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Menstrual_Information Direction'],dfProfileFirst_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Frequency Direction'],dfProfileFirst_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'],dfProfileFirst_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Contraception Direction'],dfProfileFirst_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)

In [ ]:
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Age Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Height Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Weight Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Smoking Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Alcohol Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Conceive Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Month Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Children Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Positive Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Menstrual_Information Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Frequency Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Contraception Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)

In [ ]:
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Age Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Height Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Weight Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Smoking Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Alcohol Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Conceive Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Month Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Children Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Positive Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Menstrual_Information Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Frequency Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Contraception Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)

In [ ]:
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Age Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Height Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Weight Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Smoking Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Alcohol Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Conceive Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Month Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Children Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Positive Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Menstrual_Information Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Frequency Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Contraception Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)

In [ ]:
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Age Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Height Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Weight Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Smoking Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Alcohol Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Conceive Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Month Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Children Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Positive Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Menstrual_Information Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Frequency Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Contraception Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)

In [ ]:
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Age Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Height Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Weight Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Smoking Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Alcohol Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Conceive Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Month Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Children Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Positive Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Menstrual_Information Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Frequency Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Contraception Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)

In [ ]:
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Age Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Height Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Weight Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Smoking Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Alcohol Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Conceive Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Month Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Children Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Positive Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Menstrual_Information Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Frequency Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Contraception Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)

In [ ]:
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Age Direction'],dfProfileFirst_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Height Direction'],dfProfileFirst_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Weight Direction'],dfProfileFirst_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Smoking Direction'],dfProfileFirst_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Alcohol Direction'],dfProfileFirst_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Conceive Direction'],dfProfileFirst_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Month Direction'],dfProfileFirst_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Children Direction'],dfProfileFirst_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Direction'],dfProfileFirst_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Positive Direction'],dfProfileFirst_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Menstrual_Information Direction'],dfProfileFirst_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Frequency Direction'],dfProfileFirst_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'],dfProfileFirst_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Contraception Direction'],dfProfileFirst_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)

In [ ]:
contigency = pd.crosstab(dfProfileFirst_DiffLast['Age Direction'],dfProfileFirst_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Height Direction'],dfProfileFirst_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Weight Direction'],dfProfileFirst_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Smoking Direction'],dfProfileFirst_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Alcohol Direction'],dfProfileFirst_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Conceive Direction'],dfProfileFirst_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Month Direction'],dfProfileFirst_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Children Direction'],dfProfileFirst_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Direction'],dfProfileFirst_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Positive Direction'],dfProfileFirst_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Menstrual_Information Direction'],dfProfileFirst_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Frequency Direction'],dfProfileFirst_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Right_Time Direction'],dfProfileFirst_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Contraception Direction'],dfProfileFirst_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Age Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Height Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Weight Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Smoking Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Alcohol Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Conceive Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Month Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Children Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Positive Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Menstrual_Information Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Frequency Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Right_Time Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Contraception Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Age Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Height Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Weight Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Smoking Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Alcohol Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Conceive Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Month Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Children Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Positive Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Menstrual_Information Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Frequency Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Right_Time Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Contraception Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Age Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Height Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Weight Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Smoking Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Alcohol Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Conceive Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Month Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Children Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Positive Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Menstrual_Information Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Frequency Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Right_Time Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Contraception Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Age Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Height Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Weight Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Smoking Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Alcohol Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Conceive Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Month Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Children Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Positive Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Menstrual_Information Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Frequency Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Right_Time Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Contraception Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Age Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Height Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Weight Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Smoking Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Alcohol Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Conceive Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Month Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Children Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Positive Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Menstrual_Information Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Frequency Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Right_Time Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Contraception Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Age Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Height Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Weight Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Smoking Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Alcohol Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Conceive Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Month Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Children Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Positive Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Menstrual_Information Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Frequency Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Right_Time Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Contraception Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Age Direction'],dfProfileFirst_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Height Direction'],dfProfileFirst_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Weight Direction'],dfProfileFirst_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Smoking Direction'],dfProfileFirst_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Alcohol Direction'],dfProfileFirst_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Conceive Direction'],dfProfileFirst_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Month Direction'],dfProfileFirst_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Children Direction'],dfProfileFirst_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Direction'],dfProfileFirst_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Positive Direction'],dfProfileFirst_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Menstrual_Information Direction'],dfProfileFirst_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Frequency Direction'],dfProfileFirst_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Right_Time Direction'],dfProfileFirst_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileFirst_DiffLast['Contraception Direction'],dfProfileFirst_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)

(264.7605913871355,
 3.220831963968855e-58,
 2,
 array([[  27.7559322 ,  294.2440678 ],
        [ 129.81501211, 1376.18498789],
        [ 198.42905569, 2103.57094431]]))

(37.07090586906388,
 8.91569228642892e-09,
 2,
 array([[ 107.66198547, 1141.33801453],
        [  62.062954  ,  657.937046  ],
        [ 186.27506053, 1974.72493947]]))

(26.308096898640933,
 1.9376232800688753e-06,
 2,
 array([[ 185.8440678 , 1970.1559322 ],
        [  38.01355932,  402.98644068],
        [ 132.14237288, 1400.85762712]]))

(9.348217728651253,
 0.00933383914976699,
 2,
 array([[  33.35883777,  353.64116223],
        [ 312.12493947, 3308.87506053],
        [  10.51622276,  111.48377724]]))

(19.437915845290632,
 6.0132630761131436e-05,
 2,
 array([[  54.56368039,  578.43631961],
        [ 271.00823245, 2872.99176755],
        [  30.42808717,  322.57191283]]))

(0.9201907559133595,
 0.6312234378340202,
 2,
 array([[  11.89820706,  136.10179294],
        [ 260.95662233, 2985.04337767],
        [   5.14517062,   58.85482938]]))

(9.339501108978656,
 0.009374607689174282,
 2,
 array([[  32.4038835 ,  359.5961165 ],
        [ 250.38613037, 2778.61386963],
        [  15.20998613,  168.79001387]]))

(0.6233842451298164,
 0.7322069235190398,
 2,
 array([[   4.80291345,   54.19708655],
        [ 275.31276778, 3106.68723222],
        [   4.88431877,   55.11568123]]))

(0.6870511486292574,
 0.7092653419374648,
 2,
 array([[   9.37446929,  105.62553071],
        [ 236.56269459, 2665.43730541],
        [  42.06283612,  473.93716388]]))

(2.7157216754937346,
 0.2572104036602351,
 2,
 array([[   6.80410376,   88.19589624],
        [ 174.90127758, 2267.09872242],
        [   3.29461866,   42.70538134]]))

(3.087798621884639,
 0.21354679052828066,
 2,
 array([[1.98520151e+00, 9.50147985e+01],
        [6.20528967e+01, 2.96994710e+03],
        [9.61901763e-01, 4.60380982e+01]]))

(6.119017719499393,
 0.04691072931037643,
 2,
 array([[  51.66435506,  573.33564494],
        [ 193.01803051, 2141.98196949],
        [  53.31761442,  591.68238558]]))

(1.9308323084605639,
 0.38082468495468613,
 2,
 array([[  13.16240299,  145.83759701],
        [ 248.1816614 , 2749.8183386 ],
        [  26.65593561,  295.34406439]]))

(3.5919543185726255,
 0.16596519865082426,
 2,
 array([[  10.62464428,  120.37535572],
        [ 268.21143995, 3038.78856005],
        [   6.16391577,   69.83608423]]))

(15.275065006920343,
 0.00048201635957621227,
 2,
 array([[  76.97802198,  208.02197802],
        [ 341.13418161,  921.86581839],
        [ 515.88779641, 1394.11220359]]))

(1.5733787070389949,
 0.45534980485925836,
 2,
 array([[ 282.7929439 ,  764.2070561 ],
        [ 146.66338924,  396.33661076],
        [ 504.54366686, 1363.45633314]]))

(14.116502964314877,
 0.0008602809963373467,
 2,
 array([[ 484.28629265, 1308.71370735],
        [  88.59224986,  239.40775014],
        [ 361.12145749,  975.87854251]]))

(4.091360726750528,
 0.12929219437251355,
 2,
 array([[  89.94274147,  243.05725853],
        [ 813.80624639, 2199.19375361],
        [  30.25101215,   81.74898785]]))

(8.21189134405542,
 0.01647443205996196,
 2,
 array([[ 145.04279931,  391.95720069],
        [ 707.92770388, 1913.07229612],
        [  81.02949682,  218.97050318]]))

(227.78875614282822,
 3.437954176329376e-50,
 2,
 array([[  39.97455176,  108.02544824],
        [ 876.73915558, 2369.26084442],
        [  17.28629265,   46.71370735]]))

(236.44880200218745,
 4.526838688402659e-52,
 2,
 array([[ 105.87854251,  286.12145749],
        [ 778.42336611, 2103.57663389],
        [  49.69809138,  134.30190862]]))

(12.980995939027165,
 0.0015177930052057951,
 2,
 array([[  15.46018219,   41.53981781],
        [ 891.26594182, 2394.73405818],
        [  16.27387599,   43.72612401]]))

(3.951831843897722,
 0.13863427589798855,
 2,
 array([[  29.78165939,   80.21834061],
        [ 765.11790393, 2060.88209607],
        [ 135.10043668,  363.89956332]]))

(0.4287762737972265,
 0.8070350841301701,
 2,
 array([[  22.48149622,   65.51850378],
        [ 608.02228412, 1771.97771588],
        [  11.49621966,   33.50378034]]))

(7.445718824020318,
 0.024164771923951035,
 2,
 array([[  26.09708738,   69.90291262],
        [ 801.12621359, 2145.87378641],
        [  12.77669903,   34.22330097]]))

(11.326838795070532,
 0.0034706291246082033,
 2,
 array([[ 164.75997687,  445.24002313],
        [ 599.61827646, 1620.38172354],
        [ 169.62174667,  458.37825333]]))

(0.11237762109637041,
 0.9453606249807199,
 2,
 array([[  41.55882353,  115.44117647],
        [ 766.85294118, 2130.14705882],
        [  82.58823529,  229.41176471]]))

(49.396674821529864,
 1.8777957436467533e-11,
 2,
 array([[  34.49867608,   94.50132392],
        [ 854.4439541 , 2340.5560459 ],
        [  20.05736981,   54.94263019]]))

(15.049079221834534,
 0.0005396770726398847,
 2,
 array([[ 190.22564981,   93.77435019],
        [ 854.67580691,  421.32419309],
        [1300.09854327,  640.90145673]]))

(11.43159382921956,
 0.0032935248175175865,
 2,
 array([[ 703.29905741,  346.70094259],
        [ 369.06455298,  181.93544702],
        [1272.6363896 ,  627.3636104 ]]))

(74.55740318632274,
 6.457517704871958e-17,
 2,
 array([[1213.69323051,  598.30676949],
        [ 223.71608112,  110.28391888],
        [ 907.59068837,  447.40931163]]))

(12.049028545373263,
 0.0024187261234261377,
 2,
 array([[ 225.725507 ,  111.274493 ],
        [2044.9257355, 1008.0742645],
        [  74.3487575,   36.6512425]]))

(5.708279254231888,
 0.05760536189741641,
 2,
 array([[ 363.70608398,  179.29391602],
        [1777.00228506,  875.99771494],
        [ 204.29163096,  100.70836904]]))

(4.998674851798816,
 0.08213940403985355,
 2,
 array([[  96.73347047,   47.26652953],
        [2146.27387599, 1048.72612401],
        [  42.99265354,   21.00734646]]))

(7.5024256684934585,
 0.023489240018351395,
 2,
 array([[ 259.88574693,  128.11425307],
        [1962.53927449,  967.46072551],
        [ 122.57497858,   60.42502142]]))

(149.78131262180122,
 2.9881419053789696e-33,
 2,
 array([[  39.51870894,   19.48129106],
        [2265.29277349, 1116.70722651],
        [  40.18851757,   19.81148243]]))

(2.9108703311383417,
 0.23329881819514953,
 2,
 array([[  74.41358555,   36.58641445],
        [1921.34537117,  944.65462883],
        [ 343.24104328,  168.75895672]]))

(10.52211555622831,
 0.005189812144551915,
 2,
 array([[  62.46473354,   32.53526646],
        [1585.28918495,  825.71081505],
        [  30.2460815 ,   15.7539185 ]]))

(0.2916322917907308,
 0.8643165967315927,
 2,
 array([[  62.54545455,   32.45454545],
        [1970.51100478, 1022.48899522],
        [  30.94354067,   16.05645933]]))

(2.07476230675845,
 0.3543815386762901,
 2,
 array([[ 413.94173093,  204.05826907],
        [1507.06940874,  742.93059126],
        [ 423.98886033,  209.01113967]]))

(5.759789053780682,
 0.05614068385437852,
 2,
 array([[ 104.2741652 ,   51.7258348 ],
        [1965.16695958,  974.83304042],
        [ 212.55887522,  105.44112478]]))

(13.44160844841168,
 0.0012055682767968534,
 2,
 array([[  86.2371553 ,   42.7628447 ],
        [2165.95645864, 1074.04354136],
        [  50.80638607,   25.19361393]]))

(1.5877339877966703,
 0.4520931691747082,
 2,
 array([[ 121.2012454 ,  165.7987546 ],
        [ 543.50523634,  743.49476366],
        [ 827.29351826, 1131.70648174]]))

(18.455045419055985,
 9.829644369646634e-05,
 2,
 array([[ 450.17605434,  615.82394566],
        [ 233.95641098,  320.04358902],
        [ 807.86753467, 1105.13246533]]))

(30.21411892487226,
 2.7484474497420017e-07,
 2,
 array([[ 776.19473535, 1061.80526465],
        [ 140.62722898,  192.37277102],
        [ 575.17803566,  786.82196434]]))

(3.501700260101085,
 0.1736262757763738,
 2,
 array([[ 143.16105293,  195.83894707],
        [1301.54090008, 1780.45909992],
        [  47.29804699,   64.70195301]]))

(18.112866093485096,
 0.00011663827875171545,
 2,
 array([[ 231.84489103,  317.15510897],
        [1130.50778375, 1546.49221625],
        [ 129.64732522,  177.35267478]]))

(2.354139471997655,
 0.30818046693299456,
 2,
 array([[  61.46026201,   84.53973799],
        [1357.59825328, 1867.40174672],
        [  26.94148472,   37.05851528]]))

(0.5703141468334199,
 0.7518961421474262,
 2,
 array([[ 165.54316445,  226.45683555],
        [1248.75290122, 1708.24709878],
        [  77.70393433,  106.29606567]]))

(1.2996065408293593,
 0.5221484887131052,
 2,
 array([[  24.51991975,   33.48008025],
        [1425.11464603, 1945.88535397],
        [  25.36543422,   34.63456578]]))

(877.8800900696219,
 2.3483377255878802e-191,
 2,
 array([[  48.56495896,   66.43504104],
        [1225.52618172, 1676.47381828],
        [ 217.90885933,  298.09114067]]))

(1.03972950315094,
 0.5946009613754286,
 2,
 array([[  21.40534262,   73.59465738],
        [ 550.22996516, 1891.77003484],
        [  10.36469222,   35.63530778]]))

(3.0533815376293054,
 0.21725342085020813,
 2,
 array([[  39.67067004,   57.32932996],
        [1235.10745891, 1784.89254109],
        [  19.22187105,   27.77812895]]))

(10.90244729850798,
 0.004291050735877142,
 2,
 array([[ 262.25077838,  358.74922162],
        [ 961.58618738, 1315.41381262],
        [ 268.16303425,  366.83696575]]))

(9.746073049495143,
 0.007650100264587374,
 2,
 array([[  66.86959047,   92.13040953],
        [1246.97066512, 1718.02933488],
        [ 134.15974441,  184.84025559]]))

(3.793678118113591,
 0.1500421447938663,
 2,
 array([[  54.52216465,   75.47783535],
        [1371.02274036, 1897.97725964],
        [  31.45509499,   43.54490501]]))

(1.9726250202734188,
 0.3729494056838586,
 2,
 array([[ 192.5203252 ,   17.4796748 ],
        [ 868.17499032,   78.82500968],
        [1307.30468448,  118.69531552]]))

(0.7714387925124271,
 0.6799612985992884,
 2,
 array([[ 677.48819202,   61.51180798],
        [ 357.53774681,   32.46225319],
        [1332.97406117,  121.02593883]]))

(2.844089172478091,
 0.24122031662268392,
 2,
 array([[1166.12311266,  105.87688734],
        [ 215.43941154,   19.56058846],
        [ 986.4374758 ,   89.5625242 ]]))

(6.142691581189741,
 0.04635872372286067,
 2,
 array([[ 232.85791715,   21.14208285],
        [2052.63337205,  186.36662795],
        [  82.5087108 ,    7.4912892 ]]))

(0.08207575726917526,
 0.9597927736194874,
 2,
 array([[ 388.70770422,   35.29229578],
        [1758.35230352,  159.64769648],
        [ 220.93999226,   20.06000774]]))

(1.344388659269948,
 0.5105869515487416,
 2,
 array([[ 102.8189415 ,    9.1810585 ],
        [2155.52566653,  192.47433347],
        [  48.65539196,    4.34460804]]))

(10.369235050680459,
 0.005602078858810996,
 2,
 array([[ 286.9469609 ,   26.0530391 ],
        [1966.45760743,  178.54239257],
        [ 114.59543167,   10.40456833]]))

(5.263343729585615,
 0.07195805747371879,
 2,
 array([[  43.11402821,    3.88597179],
        [2249.26802508,  202.73197492],
        [  48.61794671,    4.38205329]]))

(19.128253116860577,
 7.02025053775622e-05,
 2,
 array([[  83.42547425,    7.57452575],
        [1823.44250871,  165.55749129],
        [ 461.13201703,   41.86798297]]))

(1087.7064629125439,
 6.42011213022779e-237,
 2,
 array([[  87.09252807,    7.90747193],
        [2238.73635308,  203.26364692],
        [  42.17111885,    3.82888115]]))

(2.841462292781666,
 0.24153735315736624,
 2,
 array([[  67.85423729,    6.14576271],
        [2061.30169492,  186.69830508],
        [  34.8440678 ,    3.1559322 ]]))

(2.190580616716473,
 0.33444250140050735,
 2,
 array([[ 441.87998451,   40.12001549],
        [1461.32094464,  132.67905536],
        [ 464.79907085,   42.20092915]]))

(0.21485560035097606,
 0.8981413657589314,
 2,
 array([[ 110.88871287,   10.11128713],
        [1964.8380198 ,  179.1619802 ],
        [ 238.27326733,   21.72673267]]))

(5.2300108006735195,
 0.07316739356635021,
 2,
 array([[  95.31294118,    8.68705882],
        [2187.61529412,  199.38470588],
        [  54.07176471,    4.92823529]]))

(9.431045045677642,
 0.008955185555169791,
 2,
 array([[ 193.17884131,   30.82115869],
        [1100.42947103,  175.57052897],
        [1445.39168766,  230.60831234]]))

(5.255960426818971,
 0.07222419247270438,
 2,
 array([[ 848.6070529 ,  135.3929471 ],
        [ 440.68923174,   70.31076826],
        [1449.70371537,  231.29628463]]))

(0.4495578303400579,
 0.7986927780984072,
 2,
 array([[1447.11649874,  230.88350126],
        [ 262.17128463,   41.82871537],
        [1029.71221662,  164.28778338]]))

(2.7007098833336998,
 0.2591482618037403,
 2,
 array([[ 258.72166247,   41.27833753],
        [2396.625     ,  382.375     ],
        [  83.65333753,   13.34666247]]))

(0.9565024006306447,
 0.6198664667711631,
 2,
 array([[ 409.64263224,   65.35736776],
        [2105.99433249,  336.00566751],
        [ 223.36303526,   35.63696474]]))

(2.570041900170895,
 0.2766447878393186,
 2,
 array([[ 111.09029126,   17.90970874],
        [2497.37864078,  402.62135922],
        [  52.53106796,    8.46893204]]))

(1.8153978414675136,
 0.4034515306735904,
 2,
 array([[ 307.0163728 ,   48.9836272 ],
        [2297.44836272,  366.55163728],
        [ 134.53526448,   21.46473552]]))

(2.437501877861302,
 0.2955991578301308,
 2,
 array([[  46.55885167,    7.44114833],
        [2606.43349282,  416.56650718],
        [  50.0076555 ,    7.9923445 ]]))

(11.299241515961144,
 0.0035188510180617595,
 2,
 array([[  91.3596713 ,   14.6403287 ],
        [2230.55499368,  357.44500632],
        [ 405.08533502,   64.91466498]]))

(6.490956436358605,
 0.03894993333658974,
 2,
 array([[  75.0559322,   11.9440678],
        [1922.1220339,  305.8779661],
        [  38.8220339,    6.1779661]]))

(632.0281936527059,
 5.712438594411314e-138,
 2,
 array([[  83.65333753,   13.34666247],
        [2614.81360202,  417.18639798],
        [  40.53306045,    6.46693955]]))

(7.911974172716063,
 0.01913976661973341,
 2,
 array([[ 482.94710327,   77.05289673],
        [1766.20654912,  281.79345088],
        [ 489.84634761,   78.15365239]]))

(8.803801967079236,
 0.012254023051499677,
 2,
 array([[ 122.64260393,   19.35739607],
        [2302.5717048 ,  363.4282952 ],
        [ 254.78569127,   40.21430873]]))

(2.104165893121971,
 0.34920960608485563,
 2,
 array([[ 101.9553144 ,   16.0446856 ],
        [2549.74688797,  401.25311203],
        [  55.29779764,    8.70220236]]))

(3.03286923985418,
 0.5523399595149674,
 4,
 array([[ 53.30612245, 117.06122449, 113.63265306],
        [236.87438919, 520.18051164, 504.94509917],
        [362.81948836, 796.75826387, 773.42224777]]))

(10.488033538672864,
 0.032962224641916796,
 4,
 array([[198.20868066, 435.26990515, 422.5214142 ],
        [102.670595  , 225.46651337, 218.86289164],
        [352.12072435, 773.26358149, 750.61569416]]))

(8.316182790502562,
 0.08065900955884665,
 4,
 array([[338.41879851, 743.17390055, 721.40730095],
        [ 60.81402702, 133.5487209 , 129.63725208],
        [253.76717448, 557.27737856, 540.95544697]]))

(2.7664445544950294,
 0.5976387483906259,
 4,
 array([[  64.19258408,  140.96809428,  136.83932164],
        [ 567.97298074, 1247.27910319, 1210.74791607],
        [  20.83443518,   45.75280253,   44.41276229]]))

(7.088329453507354,
 0.13129339619200556,
 4,
 array([[ 101.3567117 ,  222.58120149,  216.06208681],
        [ 493.6447255 , 1084.05288876, 1052.30238574],
        [  57.99856281,  127.36590974,  123.63552745]]))

(26.301900123819205,
 2.750429735928578e-05,
 4,
 array([[  25.91206179,   58.06298277,   56.02495544],
        [ 585.4275104 , 1311.80867499, 1265.76381462],
        [  11.66042781,   26.12834225,   25.21122995]]))

(32.750659884517994,
 1.3434379953925403e-06,
 4,
 array([[  73.01437195,  160.34090256,  155.6447255 ],
        [ 545.82466226, 1198.64098879, 1163.53434895],
        [  34.16096579,   75.01810865,   72.82092555]]))

(9.95531053497104,
 0.04118723617713877,
 4,
 array([[  10.61862917,   23.49121265,   22.89015817],
        [ 614.20386643, 1358.78119508, 1324.01493849],
        [  11.17750439,   24.72759227,   24.09490334]]))

(9.15928826098737,
 0.0572390379331885,
 4,
 array([[  20.79436538,   45.74760383,   44.45803079],
        [ 529.7879756 , 1165.53354633, 1132.67847807],
        [  94.41765902,  207.71884984,  201.86349114]]))

(6.853002451577312,
 0.14386329871074977,
 4,
 array([[  15.69029703,   38.23128713,   39.07841584],
        [ 402.71762376,  981.26970297, 1003.01267327],
        [   7.59207921,   18.4990099 ,   18.90891089]]))

(3.549853278306986,
 0.47033864208702725,
 4,
 array([[  17.34450532,   37.98001934,   36.67547535],
        [ 559.17176926, 1224.44279729, 1182.38543345],
        [   8.48372543,   18.57718337,   17.9390912 ]]))

(26.5448431293087,
 2.4567344619383957e-05,
 4,
 array([[115.43403277, 253.49525726, 246.07070997],
        [417.43949411, 916.70480023, 889.85570566],
        [120.12647312, 263.79994251, 256.07358436]]))

(334.1661628112126,
 4.594769476939525e-71,
 4,
 array([[  29.84392067,   65.53779822,   63.61828112],
        [ 562.71744754, 1235.73785571, 1199.54469675],
        [  60.43863179,  132.72434608,  128.83702213]]))

(12.250290556304341,
 0.015583927843016866,
 4,
 array([[  24.00521739,   53.17043478,   51.82434783],
        [ 604.22434783, 1338.32869565, 1304.44695652],
        [  13.77043478,   30.50086957,   29.72869565]]))

(2.007396593589471,
 0.3665214265317454,
 2,
 array([[ 253.27546955,   36.72453045],
        [1113.53870233,  161.46129767],
        [1702.18582812,  246.81417188]]))

(7.628112010561327,
 0.02205852776199636,
 2,
 array([[ 926.63887308,  134.36112692],
        [ 482.97011952,   70.02988048],
        [1659.3910074 ,  240.6089926 ]]))

(18.039735343424518,
 0.0001209821345383218,
 2,
 array([[1591.26863973,  230.73136027],
        [ 286.4632897 ,   41.5367103 ],
        [1191.26807057,  172.73192943]]))

(6.634046825698739,
 0.03626060412586041,
 2,
 array([[ 297.81701764,   43.18298236],
        [2674.23961298,  387.76038702],
        [  96.94336938,   14.05663062]]))

(17.46982683172405,
 0.00016087008955635934,
 2,
 array([[ 473.36311895,   68.63688105],
        [2323.14741036,  336.85258964],
        [ 272.48947069,   39.51052931]]))

(48.8407756883375,
 2.4794783089793465e-11,
 2,
 array([[ 122.83053839,   18.16946161],
        [2784.15887026,  411.84112974],
        [  54.01059135,    7.98940865]]))

(42.150378640586325,
 7.033339366764042e-10,
 2,
 array([[ 338.86511098,   49.13488902],
        [2571.18269778,  372.81730222],
        [ 158.95219124,   23.04780876]]))

(1.1609589915405985,
 0.5596299620214009,
 2,
 array([[  50.62583454,    7.37416546],
        [2904.00261248,  422.99738752],
        [  52.37155298,    7.62844702]]))

(0.030646674291729653,
 0.984793467809809,
 2,
 array([[  98.59038572,   14.40961428],
        [2491.80656304,  364.19343696],
        [ 440.60305124,   64.39694876]]))

(2.9395388601968744,
 0.22997850519538435,
 2,
 array([[  82.16705882,   11.83294118],
        [2107.49764706,  303.50235294],
        [  39.33529412,    5.66470588]]))

(11.201862709419522,
 0.0036944212970001634,
 2,
 array([[  81.15608043,   11.84391957],
        [2611.82955634,  381.17044366],
        [  41.01436323,    5.98563677]]))

(0.8591482087555702,
 0.6507862027043196,
 2,
 array([[ 544.97894138,   79.02105862],
        [1967.6883893 ,  285.3116107 ],
        [ 556.33266932,   80.66733068]]))

(0.5835862046460223,
 0.74692305663313,
 2,
 array([[ 137.24985507,   19.75014493],
        [2599.00521739,  373.99478261],
        [ 279.74492754,   40.25507246]]))

(944.4990362960383,
 8.028606761669e-206,
 2,
 array([[ 114.41064314,   16.58935686],
        [2888.21371656,  418.78628344],
        [  66.3756403 ,    9.6243597 ]]))

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffSecond['Age Direction'],dfProfileLast_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Height Direction'],dfProfileLast_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Weight Direction'],dfProfileLast_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Smoking Direction'],dfProfileLast_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Alcohol Direction'],dfProfileLast_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Conceive Direction'],dfProfileLast_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Month Direction'],dfProfileLast_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Children Direction'],dfProfileLast_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Direction'],dfProfileLast_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Positive Direction'],dfProfileLast_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Menstrual_Information Direction'],dfProfileLast_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Frequency Direction'],dfProfileLast_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Right_Time Direction'],dfProfileLast_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Contraception Direction'],dfProfileLast_DiffSecond['Gender']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Age Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Height Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Weight Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Smoking Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Alcohol Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Conceive Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Month Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Children Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Positive Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Menstrual_Information Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Frequency Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Right_Time Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Contraception Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Age Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Height Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Weight Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Smoking Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Alcohol Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Conceive Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Month Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Children Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Positive Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Menstrual_Information Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Frequency Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Right_Time Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Contraception Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Age Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Height Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Weight Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Smoking Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Alcohol Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Conceive Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Month Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Children Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Positive Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Menstrual_Information Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Frequency Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Right_Time Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Contraception Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Age Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Height Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Weight Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Smoking Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Alcohol Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Conceive Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Month Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Children Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Positive Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Menstrual_Information Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Frequency Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Right_Time Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Contraception Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Age Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Height Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Weight Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Smoking Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Alcohol Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Conceive Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Month Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Children Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Positive Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Menstrual_Information Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Frequency Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Right_Time Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Contraception Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Age Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Height Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Weight Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Smoking Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Alcohol Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Conceive Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Month Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Children Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Positive Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Menstrual_Information Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Frequency Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Right_Time Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Contraception Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Age Direction'],dfProfileLast_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Height Direction'],dfProfileLast_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Weight Direction'],dfProfileLast_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Smoking Direction'],dfProfileLast_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Alcohol Direction'],dfProfileLast_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Conceive Direction'],dfProfileLast_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Month Direction'],dfProfileLast_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Children Direction'],dfProfileLast_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Direction'],dfProfileLast_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Positive Direction'],dfProfileLast_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Menstrual_Information Direction'],dfProfileLast_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Frequency Direction'],dfProfileLast_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Right_Time Direction'],dfProfileLast_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffSecond['Contraception Direction'],dfProfileLast_DiffSecond['Contraception']) 
stats.chi2_contingency(contigency)

(700.0613954891362,
 9.629405440110647e-153,
 2,
 array([[  70.46368039,  364.53631961],
        [ 243.95012107, 1262.04987893],
        [ 354.58619855, 1834.41380145]]))

(62.89475367374173,
 2.2007857705921392e-14,
 2,
 array([[ 210.25714286, 1087.74285714],
        [ 116.62953995,  603.37046005],
        [ 342.11331719, 1769.88668281]]))

(33.701951862167014,
 4.805229542478556e-08,
 2,
 array([[ 326.56271186, 1689.43728814],
        [  71.43559322,  369.56440678],
        [ 271.00169492, 1401.99830508]]))

(14.444801907361176,
 0.0007300475027486001,
 2,
 array([[  62.8503632 ,  325.1496368 ],
        [ 586.54939467, 3034.45060533],
        [  19.60024213,  101.39975787]]))

(134.18153022226815,
 7.292071621434175e-30,
 2,
 array([[ 111.93196126,  579.06803874],
        [ 509.28232446, 2634.71767554],
        [  47.78571429,  247.21428571]]))

(1.1451436124257859,
 0.564072885506026,
 2,
 array([[  24.35280509,  123.64719491],
        [ 534.11625217, 2711.88374783],
        [  10.53094274,   53.46905726]]))

(117.96587207984969,
 2.421231700700572e-26,
 2,
 array([[  66.07323162,  334.92676838],
        [ 499.09181692, 2529.90818308],
        [  28.83495146,  146.16504854]]))

(70.02078111350683,
 6.239942272591712e-16,
 2,
 array([[   9.70694087,   49.29305913],
        [ 556.42159383, 2825.57840617],
        [   9.8714653 ,   50.1285347 ]]))

(66.01061034500724,
 4.634235396481741e-15,
 2,
 array([[  18.81403906,   96.18596094],
        [ 474.76818568, 2427.23181432],
        [  84.41777526,  431.58222474]]))

(8.485416671587302,
 0.014368624039191754,
 2,
 array([[  15.26325978,   79.73674022],
        [ 392.34610918, 2049.65389082],
        [   7.39063105,   38.60936895]]))

(2.826084511741165,
 0.24340166548434639,
 2,
 array([[   7.4215995 ,   89.5784005 ],
        [ 231.98236776, 2800.01763224],
        [   3.59603275,   43.40396725]]))

(224.1213922470481,
 2.151087295586203e-49,
 2,
 array([[ 102.98196949,  522.01803051],
        [ 384.740638  , 1950.259362  ],
        [ 106.27739251,  538.72260749]]))

(10.420953367468643,
 0.005459070817054031,
 2,
 array([[  30.28973843,  151.71026157],
        [ 498.94854843, 2499.05145157],
        [  49.76171314,  249.23828686]]))

(16.17275735040317,
 0.00030770203096045753,
 2,
 array([[  21.6220831 ,  109.3779169 ],
        [ 545.83380763, 2761.16619237],
        [  12.54410928,   63.45589072]]))

(10.571146067670126,
 0.005064129439039771,
 2,
 array([[ 111.15529208,  263.84470792],
        [ 374.37102371,  888.62897629],
        [ 539.47368421, 1280.52631579]]))

(4.290642554799367,
 0.1170304317707844,
 2,
 array([[ 323.68421053,  768.31578947],
        [ 160.95286293,  382.04713707],
        [ 540.36292655, 1282.63707345]]))

(13.95116027055749,
 0.0009344241177466934,
 2,
 array([[ 498.86495084, 1184.13504916],
        [  97.2238288 ,  230.7761712 ],
        [ 428.91122036, 1018.08877964]]))

(4.946358909110525,
 0.0843163523648235,
 2,
 array([[  99.5951417 ,  236.4048583 ],
        [ 893.09572007, 2119.90427993],
        [  32.30913823,   76.69086177]]))

(7.266674650101137,
 0.026427838783452853,
 2,
 array([[ 175.18074031,  415.81925969],
        [ 776.90138809, 1844.09861191],
        [  72.9178716 ,  173.0821284 ]]))

(251.04685825062998,
 3.0610285574089815e-55,
 2,
 array([[  43.86928861,  104.13071139],
        [ 962.16020821, 2283.83979179],
        [  18.97050318,   45.02949682]]))

(261.2778794503733,
 1.837508495460363e-57,
 2,
 array([[ 118.86205899,  282.13794101],
        [ 854.26547137, 2027.73452863],
        [  51.87246964,  123.12753036]]))

(6.700042935007641,
 0.03508360093542364,
 2,
 array([[  16.93417573,   40.06582427],
        [ 976.24037614, 2309.75962386],
        [  17.82544813,   42.17455187]]))

(3.158832234991282,
 0.20609539857828285,
 2,
 array([[  32.63173217,   77.36826783],
        [ 838.33886463, 1987.66113537],
        [ 148.0294032 ,  350.9705968 ]]))

(0.35734300536811847,
 0.836380603058067,
 2,
 array([[  24.65260645,   63.34739355],
        [ 666.74094708, 1713.25905292],
        [  12.60644648,   32.39355352]]))

(7.585169397479487,
 0.022537274439359527,
 2,
 array([[  28.45825243,   67.54174757],
        [ 873.60906149, 2073.39093851],
        [  13.93268608,   33.06731392]]))

(12.932665365921297,
 0.0015549176655367113,
 2,
 array([[ 180.81260844,  429.18739156],
        [ 658.03932909, 1561.96067091],
        [ 186.14806246,  441.85193754]]))

(0.27777170283254204,
 0.8703273694249288,
 2,
 array([[  52.13903743,  127.86096257],
        [ 839.14884135, 2057.85115865],
        [  83.71212121,  205.28787879]]))

(60.29853103286175,
 8.060098566078528e-14,
 2,
 array([[  37.72462489,   91.27537511],
        [ 934.34245366, 2260.65754634],
        [  21.93292145,   53.06707855]]))

(7.128305124747193,
 0.02832097557801833,
 2,
 array([[ 255.80605541,  123.19394459],
        [ 861.23621822,  414.76378178],
        [1245.95772636,  600.04227364]]))

(9.390607724652309,
 0.0091380902246246,
 2,
 array([[ 734.34561554,  353.65438446],
        [ 371.89745787,  179.10254213],
        [1256.75692659,  605.24307341]]))

(85.96628841422566,
 2.1510854168055603e-19,
 2,
 array([[1145.39017424,  551.60982576],
        [ 225.43330477,  108.56669523],
        [ 992.17652099,  477.82347901]]))

(5.512296948335305,
 0.06353600828672078,
 2,
 array([[ 227.45815481,  109.54184519],
        [2060.6223936 ,  992.3776064 ],
        [  74.91945159,   36.08054841]]))

(6.677554064588653,
 0.035480322487928984,
 2,
 array([[ 404.29505855,  194.70494145],
        [1790.64238789,  862.35761211],
        [ 168.06255356,   80.93744644]]))

(3.1050478191173916,
 0.2117129545908811,
 2,
 array([[  97.41052013,   46.58947987],
        [2161.29591537, 1033.70408463],
        [  43.2935645 ,   20.7064355 ]]))

(9.117491834434627,
 0.01047518746182302,
 2,
 array([[ 267.95515567,  129.04484433],
        [1977.60354185,  952.39645815],
        [ 117.44130249,   56.55869751]]))

(46.21827288238353,
 9.200884141208525e-11,
 2,
 array([[  39.82205084,   19.17794916],
        [2282.6809483 , 1099.3190517 ],
        [  40.49700086,   19.50299914]]))

(3.2396768209521785,
 0.19793068002400502,
 2,
 array([[  74.9544282,   36.0455718],
        [1935.3098309,  930.6901691],
        [ 345.7357409,  166.2642591]]))

(13.649650953513808,
 0.0010864655384081156,
 2,
 array([[  62.8742163 ,   32.1257837 ],
        [1595.68142633,  815.31857367],
        [  30.44435737,   15.55564263]]))

(0.8831075668519127,
 0.6430365049940434,
 2,
 array([[  62.93939394,   32.06060606],
        [1982.92216906, 1010.07783094],
        [  31.138437  ,   15.861563  ]]))

(0.744191032930428,
 0.6892884009882219,
 2,
 array([[ 417.11910883,  200.88089117],
        [1518.63753213,  731.36246787],
        [ 427.24335904,  205.75664096]]))

(11.995539146113632,
 0.0024842870225467955,
 2,
 array([[ 120.48681898,   58.51318102],
        [1978.94551845,  961.05448155],
        [ 198.56766257,   96.43233743]]))

(10.451801143975059,
 0.0053755167396096985,
 2,
 array([[  86.87373004,   42.12626996],
        [2181.94484761, 1058.05515239],
        [  51.18142235,   24.81857765]]))

(1.8061937629454283,
 0.40531250932164464,
 2,
 array([[ 114.39456553,  267.60543447],
        [ 385.40786867,  901.59213133],
        [ 558.19756581, 1305.80243419]]))

(17.640048415052497,
 0.00014774478365301547,
 2,
 array([[ 331.20520804,  774.79479196],
        [ 165.90206623,  388.09793377],
        [ 560.89272573, 1312.10727427]]))

(26.334327177629646,
 1.9123769966047736e-06,
 2,
 array([[ 515.37446929, 1205.62553071],
        [  99.72091707,  233.27908293],
        [ 442.90461364, 1036.09538636]]))

(6.29806600833926,
 0.04289358473660606,
 2,
 array([[ 101.51769035,  237.48230965],
        [ 922.94254175, 2159.05745825],
        [  33.5397679 ,   78.4602321 ]]))

(7.953930997817684,
 0.01874242704830092,
 2,
 array([[ 180.8751769 ,  423.1248231 ],
        [ 801.66034532, 1875.33965468],
        [  75.46447778,  176.53552222]]))

(0.314647848886922,
 0.8544272441170531,
 2,
 array([[  43.52372635,  102.47627365],
        [ 961.39737991, 2263.60262009],
        [  19.07889374,   44.92110626]]))

(6.385973678415375,
 0.041049080649405274,
 2,
 array([[ 120.08434758,  280.91565242],
        [ 885.50976507, 2071.49023493],
        [  52.40588735,  122.59411265]]))

(3.370973785306378,
 0.18535416240205133,
 2,
 array([[  17.35511608,   40.64488392],
        [1008.69131556, 2362.30868444],
        [  17.95356836,   42.04643164]]))

(247.90010576626085,
 1.4763046961032145e-54,
 2,
 array([[  34.43815454,   80.56184546],
        [ 869.03934333, 2032.96065667],
        [ 154.52250212,  361.47749788]]))

(3.5526929494705226,
 0.16925539788399807,
 2,
 array([[   4.85481998,   90.14518002],
        [ 124.79442509, 2317.20557491],
        [   2.35075494,   43.64924506]]))

(0.6187275899797662,
 0.7339137273178042,
 2,
 array([[  27.59165613,   69.40834387],
        [ 859.0391909 , 2160.9608091 ],
        [  13.36915297,   33.63084703]]))

(17.6388207630429,
 0.00014783550108280526,
 2,
 array([[ 185.96603453,  435.03396547],
        [ 681.87545995, 1595.12454005],
        [ 190.15850552,  444.84149448]]))

(11.12412731561507,
 0.00384084202987395,
 2,
 array([[  53.77955272,  127.22044728],
        [ 880.97444089, 2084.02555911],
        [  88.24600639,  208.75399361]]))

(4.79902746747127,
 0.09076207709675942,
 2,
 array([[  38.61830743,   91.38169257],
        [ 971.10189983, 2297.89810017],
        [  22.27979275,   52.72020725]]))

(2.5597925036846534,
 0.27806614780728467,
 2,
 array([[ 263.25512969,   14.74487031],
        [ 896.77197058,   50.22802942],
        [1285.97289973,   72.02710027]]))

(2.0993800002527117,
 0.35004624658539574,
 2,
 array([[ 738.62950058,   41.37049942],
        [ 369.31475029,   20.68524971],
        [1338.05574913,   74.94425087]]))

(1.0291783682202953,
 0.5977461077836048,
 2,
 array([[1140.14092141,   63.85907859],
        [ 222.53581107,   12.46418893],
        [1083.32326752,   60.67673248]]))

(3.347540388862136,
 0.1875386738267546,
 2,
 array([[ 234.84630275,   13.15369725],
        [2120.24545103,  118.75454897],
        [  90.90824623,    5.09175377]]))

(1.2050303200758867,
 0.5474330214435659,
 2,
 array([[ 441.28377855,   24.71622145],
        [1816.27100271,  101.72899729],
        [ 188.44521874,   10.55478126]]))

(3.240058680258818,
 0.19789289279535274,
 2,
 array([[ 106.02785515,    5.97214485],
        [2222.7982491 ,  125.2017509 ],
        [  50.17389574,    2.82610426]]))

(0.5295195747308838,
 0.7673902646748214,
 2,
 array([[ 298.29268293,   16.70731707],
        [2031.2311266 ,  113.7688734 ],
        [ 116.47619048,    6.52380952]]))

(1.1671023205918083,
 0.5579136039072641,
 2,
 array([[  44.55054859,    2.44945141],
        [2324.21159875,  127.78840125],
        [  50.23785266,    2.76214734]]))

(17.178744732988527,
 0.0001860728365602395,
 2,
 array([[  86.17344173,    4.82655827],
        [1883.50522648,  105.49477352],
        [ 476.32133178,   26.67866822]]))

(83.74539842857665,
 6.530069279163155e-19,
 2,
 array([[  89.96128533,    5.03871467],
        [2312.47851336,  129.52148664],
        [  43.56020132,    2.43979868]]))

(8.533630813774746,
 0.014026380418050937,
 2,
 array([[7.00491525e+01, 3.95084746e+00],
        [2.12797966e+03, 1.20020339e+02],
        [3.59711864e+01, 2.02881356e+00]]))

(1.83089702819329,
 0.40033702901699675,
 2,
 array([[ 456.43515292,   25.56484708],
        [1509.4556717 ,   84.5443283 ],
        [ 480.10917538,   26.89082462]]))

(0.791626119339924,
 0.6731325197916529,
 2,
 array([[ 134.40792079,    7.59207921],
        [2029.37029703,  114.62970297],
        [ 226.22178218,   12.77821782]]))

(0.8444293447583072,
 0.6555932865155312,
 2,
 array([[  98.45333333,    5.54666667],
        [2259.69333333,  127.30666667],
        [  55.85333333,    3.14666667]]))

(3.0498326540756637,
 0.21763926662551256,
 2,
 array([[ 265.42821159,   34.57178841],
        [1128.95465995,  147.04534005],
        [1415.61712846,  184.38287154]]))

(5.400925199785017,
 0.06717443066661652,
 2,
 array([[ 889.18450882,  115.81549118],
        [ 452.1127204 ,   58.8872796 ],
        [1468.70277078,  191.29722922]]))

(2.475079115809984,
 0.2900971077028515,
 2,
 array([[1375.80289673,  179.19710327],
        [ 268.96725441,   35.03274559],
        [1165.22984887,  151.77015113]]))

(2.40852738044295,
 0.2999127469222983,
 2,
 array([[ 268.96725441,   35.03274559],
        [2458.75      ,  320.25      ],
        [  82.28274559,   10.71725441]]))

(0.2568067557651151,
 0.8794985373240859,
 2,
 array([[ 462.72984887,   60.27015113],
        [2160.58564232,  281.41435768],
        [ 186.68450882,   24.31549118]]))

(1.9795677529217377,
 0.37165700617025244,
 2,
 array([[ 114.01262136,   14.98737864],
        [2563.07443366,  336.92556634],
        [  53.91294498,    7.08705502]]))

(1.2688206988189492,
 0.5302480572353626,
 2,
 array([[ 322.05289673,   41.94710327],
        [2357.00251889,  306.99748111],
        [ 130.94458438,   17.05541562]]))

(1.8576289382864264,
 0.3950217433488569,
 2,
 array([[  47.74736842,    6.25263158],
        [2672.96842105,  350.03157895],
        [  51.28421053,    6.71578947]]))

(5.747989267065487,
 0.05647288691984129,
 2,
 array([[  93.73830594,   12.26169406],
        [2288.62958281,  299.37041719],
        [ 415.63211125,   54.36788875]]))

(5.632934295913271,
 0.05981689409604704,
 2,
 array([[  77.04661017,    9.95338983],
        [1973.10169492,  254.89830508],
        [  39.85169492,    5.14830508]]))

(54.823673715277444,
 1.2450606683027014e-12,
 2,
 array([[  85.82178841,   11.17821159],
        [2682.59445844,  349.40554156],
        [  41.58375315,    5.41624685]]))

(7.802600947910299,
 0.020215604476638404,
 2,
 array([[ 495.46599496,   64.53400504],
        [1811.98992443,  236.01007557],
        [ 502.5440806 ,   65.4559194 ]]))

(5.47778004728338,
 0.06464205824325674,
 2,
 array([[ 141.64357074,   18.35642926],
        [2360.13599742,  305.86400258],
        [ 245.22043184,   31.77956816]]))

(2.5295508257557726,
 0.28230269057031077,
 2,
 array([[ 104.47877434,   13.52122566],
        [2612.85477178,  338.14522822],
        [  56.66645388,    7.33354612]]))

(3.403742501219312,
 0.4926645995755916,
 4,
 array([[ 63.3515378 , 146.47312446, 170.17533774],
        [210.39379132, 486.44495545, 565.16125323],
        [306.25467088, 708.08192009, 822.66340903]]))

(7.877557970879337,
 0.09616778489644075,
 4,
 array([[182.05231388, 420.91750503, 489.03018109],
        [ 91.19287151, 210.84420811, 244.96292038],
        [306.7548146 , 709.23828686, 824.00689853]]))

(8.470384484943299,
 0.07579001855869735,
 4,
 array([[281.24748491, 650.26358149, 755.4889336 ],
        [ 54.0155217 , 124.88761138, 145.09686692],
        [244.73699339, 565.84880713, 657.41419948]]))

(1.2015334776944278,
 0.8778460761594222,
 4,
 array([[  57.34981316,  132.5967232 ,  154.05346364],
        [ 504.47829836, 1166.38861742, 1355.13308422],
        [  18.17188847,   42.01465938,   48.81345214]]))

(1.4193568285907818,
 0.8408238253616918,
 4,
 array([[  99.02845645,  228.96062087,  266.01092268],
        [ 438.45932739, 1013.74820351, 1177.7924691 ],
        [  42.51221615,   98.29117563,  114.19660822]]))

(14.859370386196836,
 0.005001958389049389,
 4,
 array([[  23.08377897,   54.19489008,   62.72133096],
        [ 521.5285205 , 1224.41740939, 1417.05407011],
        [  10.38770053,   24.38770053,   28.22459893]]))

(44.72940391499341,
 4.5257816364984075e-09,
 4,
 array([[  66.35240011,  153.41132509,  178.23627479],
        [ 484.80597873, 1120.90485772, 1302.28916355],
        [  28.84162116,   66.68381719,   77.47456166]]))

(10.993084469631441,
 0.026641845416138045,
 4,
 array([[   9.41652021,   21.95518453,   25.62829525],
        [ 544.67135325, 1269.9340949 , 1482.39455185],
        [   9.91212654,   23.11072056,   26.9771529 ]]))

(11.596031353723903,
 0.020622245246424642,
 4,
 array([[  18.47313389,   42.81382515,   49.71304095],
        [ 470.64885274, 1090.78826605, 1266.56288121],
        [  83.87801336,  194.3979088 ,  225.72407784]]))

(2.5613842836256233,
 0.6336787389031779,
 4,
 array([[  13.66455446,   34.91643564,   44.4190099 ],
        [ 350.72356436,  896.18851485, 1140.08792079],
        [   6.61188119,   16.8950495 ,   21.49306931]]))

(3.9064729847341777,
 0.4188113046681249,
 4,
 array([[  15.35804061,   35.34128263,   41.30067676],
        [ 495.12987432, 1139.37222043, 1331.49790525],
        [   7.51208508,   17.28649694,   20.20141798]]))

(50.19673139620205,
 3.284971339616895e-10,
 4,
 array([[102.52946249, 237.05518827, 275.41534924],
        [370.77321069, 857.25323369, 995.97355562],
        [106.69732682, 246.69157804, 286.61109514]]))

(96.78675512265146,
 4.749981181738861e-20,
 4,
 array([[  30.34205231,   70.15291751,   81.50503018],
        [ 499.81029031, 1155.59586088, 1342.59384881],
        [  49.84765737,  115.25122162,  133.90112101]]))

(7.426656368922215,
 0.1149872639437568,
 4,
 array([[  21.31304348,   49.69304348,   57.99391304],
        [ 536.46086957, 1250.80086957, 1459.73826087],
        [  12.22608696,   28.50608696,   33.26782609]]))

(5.177826112490106,
 0.07510162698154471,
 2,
 array([[ 347.20119522,   37.79880478],
        [1149.82214001,  125.17785999],
        [1671.97666477,  182.02333523]]))

(3.9879496120764215,
 0.13615316604497024,
 2,
 array([[ 991.10159363,  107.89840637],
        [ 498.70717131,   54.29282869],
        [1679.19123506,  182.80876494]]))

(19.311538807713774,
 6.405494009572737e-05,
 2,
 array([[1534.89982925,  167.10017075],
        [ 295.7973819 ,   32.2026181 ],
        [1338.30278884,  145.69721116]]))

(3.6172734609051886,
 0.1638773936487669,
 2,
 array([[ 309.3247012,   33.6752988],
        [2761.3767786,  300.6232214],
        [  98.2985202,   10.7014798]]))

(10.234412754950627,
 0.005992740988321716,
 2,
 array([[ 536.58366534,   58.41633466],
        [2398.84462151,  261.15537849],
        [ 233.57171315,   25.42828685]]))

(25.24064119704498,
 3.3041853720991994e-06,
 2,
 array([[ 126.89585172,   14.10414828],
        [2876.30597234,  319.69402766],
        [  55.79817593,    6.20182407]]))

(54.63719363972632,
 1.3667344700803063e-12,
 2,
 array([[ 358.02305065,   38.97694935],
        [2654.96186682,  289.03813318],
        [ 156.01508253,   16.98491747]]))

(0.7432245301772827,
 0.6896215810552337,
 2,
 array([[  52.29259797,    5.70740203],
        [2999.61161103,  327.38838897],
        [  54.095791  ,    5.904209  ]]))

(0.26968720379516475,
 0.8738525698849373,
 2,
 array([[ 101.81059298,   11.18940702],
        [2573.19516408,  282.80483592],
        [ 454.99424295,   50.00575705]]))

(2.0735299421654596,
 0.354599969596349,
 2,
 array([[  85.11607843,    8.88392157],
        [2183.13686275,  227.86313725],
        [  40.74705882,    4.25294118]]))

(7.778710859406649,
 0.020458528748834477,
 2,
 array([[  83.85732525,    9.14267475],
        [2698.76316629,  294.23683371],
        [  42.37950846,    4.62049154]]))

(3.984009331868455,
 0.13642167126728388,
 2,
 array([[ 562.73648264,   61.26351736],
        [2031.803358  ,  221.196642  ],
        [ 574.46015936,   62.53984064]]))

(5.408181233462469,
 0.06693116225880126,
 2,
 array([[ 162.62608696,   17.37391304],
        [2686.04086957,  286.95913043],
        [ 268.33304348,   28.66695652]]))

(43.99915742986391,
 2.7906435016979584e-10,
 2,
 array([[ 118.1385885 ,   12.8614115 ],
        [2982.32299374,  324.67700626],
        [  68.53841776,    7.46158224]]))

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Age Direction'],dfProfileLast_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Height Direction'],dfProfileLast_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Weight Direction'],dfProfileLast_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Smoking Direction'],dfProfileLast_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Alcohol Direction'],dfProfileLast_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Conceive Direction'],dfProfileLast_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Month Direction'],dfProfileLast_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Children Direction'],dfProfileLast_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Direction'],dfProfileLast_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Positive Direction'],dfProfileLast_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Menstrual_Information Direction'],dfProfileLast_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Frequency Direction'],dfProfileLast_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Right_Time Direction'],dfProfileLast_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Contraception Direction'],dfProfileLast_DiffLast['Gender']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileLast_DiffLast['Age Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Height Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Weight Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Smoking Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Alcohol Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Conceive Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Month Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Children Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Positive Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Menstrual_Information Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Frequency Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Right_Time Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Contraception Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileLast_DiffLast['Age Direction'],dfProfileLast_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Height Direction'],dfProfileLast_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Weight Direction'],dfProfileLast_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Smoking Direction'],dfProfileLast_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Alcohol Direction'],dfProfileLast_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Conceive Direction'],dfProfileLast_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Month Direction'],dfProfileLast_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Children Direction'],dfProfileLast_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Direction'],dfProfileLast_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Positive Direction'],dfProfileLast_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Menstrual_Information Direction'],dfProfileLast_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Frequency Direction'],dfProfileLast_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Right_Time Direction'],dfProfileLast_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Contraception Direction'],dfProfileLast_DiffLast['Previous_Children']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileLast_DiffLast['Age Direction'],dfProfileLast_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Height Direction'],dfProfileLast_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Weight Direction'],dfProfileLast_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Smoking Direction'],dfProfileLast_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Alcohol Direction'],dfProfileLast_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Conceive Direction'],dfProfileLast_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Month Direction'],dfProfileLast_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Children Direction'],dfProfileLast_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Direction'],dfProfileLast_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Positive Direction'],dfProfileLast_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Menstrual_Information Direction'],dfProfileLast_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Frequency Direction'],dfProfileLast_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Right_Time Direction'],dfProfileLast_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Contraception Direction'],dfProfileLast_DiffLast['STI_Tested']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileLast_DiffLast['Age Direction'],dfProfileLast_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Height Direction'],dfProfileLast_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Weight Direction'],dfProfileLast_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Smoking Direction'],dfProfileLast_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Alcohol Direction'],dfProfileLast_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Conceive Direction'],dfProfileLast_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Month Direction'],dfProfileLast_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Children Direction'],dfProfileLast_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Direction'],dfProfileLast_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Positive Direction'],dfProfileLast_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Menstrual_Information Direction'],dfProfileLast_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Frequency Direction'],dfProfileLast_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Right_Time Direction'],dfProfileLast_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Contraception Direction'],dfProfileLast_DiffLast['STI_Positive']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileLast_DiffLast['Age Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Height Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Weight Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Smoking Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Alcohol Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Conceive Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Month Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Children Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Positive Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Menstrual_Information Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Frequency Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Right_Time Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Contraception Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileLast_DiffLast['Age Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Height Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Weight Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Smoking Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Alcohol Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Conceive Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Month Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Children Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Positive Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Menstrual_Information Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Frequency Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Right_Time Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Contraception Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
stats.chi2_contingency(contigency)
##
contigency = pd.crosstab(dfProfileLast_DiffLast['Age Direction'],dfProfileLast_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Height Direction'],dfProfileLast_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Weight Direction'],dfProfileLast_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Smoking Direction'],dfProfileLast_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Alcohol Direction'],dfProfileLast_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Conceive Direction'],dfProfileLast_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Month Direction'],dfProfileLast_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Children Direction'],dfProfileLast_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Direction'],dfProfileLast_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Positive Direction'],dfProfileLast_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Menstrual_Information Direction'],dfProfileLast_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Frequency Direction'],dfProfileLast_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Right_Time Direction'],dfProfileLast_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)
contigency = pd.crosstab(dfProfileLast_DiffLast['Contraception Direction'],dfProfileLast_DiffLast['Contraception']) 
stats.chi2_contingency(contigency)

(518.8603210711149,
 2.1424605811048715e-113,
 2,
 array([[  52.15932203,  269.84067797],
        [ 243.95012107, 1262.04987893],
        [ 372.8905569 , 1929.1094431 ]]))

(183.53925029570087,
 1.3962339439295801e-40,
 2,
 array([[ 202.31985472, 1046.68014528],
        [ 116.62953995,  603.37046005],
        [ 350.05060533, 1810.94939467]]))

(188.0944611187029,
 1.4315506872323344e-41,
 2,
 array([[ 349.24067797, 1806.75932203],
        [  71.43559322,  369.56440678],
        [ 248.32372881, 1284.67627119]]))

(14.415541064978106,
 0.000740806920692048,
 2,
 array([[  62.68837772,  324.31162228],
        [ 586.54939467, 3034.45060533],
        [  19.7622276 ,  102.2377724 ]]))

(151.71047514376318,
 1.138908670050192e-33,
 2,
 array([[ 102.53680387,  530.46319613],
        [ 509.28232446, 2634.71767554],
        [  57.18087167,  295.81912833]]))

(1.1451436124257859,
 0.564072885506026,
 2,
 array([[  24.35280509,  123.64719491],
        [ 534.11625217, 2711.88374783],
        [  10.53094274,   53.46905726]]))

(113.45088981535095,
 2.314473928893194e-25,
 2,
 array([[  64.59029126,  327.40970874],
        [ 499.09181692, 2529.90818308],
        [  30.31789182,  153.68210818]]))

(70.02078111350683,
 6.239942272591712e-16,
 2,
 array([[   9.70694087,   49.29305913],
        [ 556.42159383, 2825.57840617],
        [   9.8714653 ,   50.1285347 ]]))

(66.01061034500724,
 4.634235396481741e-15,
 2,
 array([[  18.81403906,   96.18596094],
        [ 474.76818568, 2427.23181432],
        [  84.41777526,  431.58222474]]))

(8.485416671587302,
 0.014368624039191754,
 2,
 array([[  15.26325978,   79.73674022],
        [ 392.34610918, 2049.65389082],
        [   7.39063105,   38.60936895]]))

(2.826084511741165,
 0.24340166548434639,
 2,
 array([[   7.4215995 ,   89.5784005 ],
        [ 231.98236776, 2800.01763224],
        [   3.59603275,   43.40396725]]))

(224.1213922470481,
 2.151087295586203e-49,
 2,
 array([[ 102.98196949,  522.01803051],
        [ 384.740638  , 1950.259362  ],
        [ 106.27739251,  538.72260749]]))

(10.439418835967194,
 0.005408900627355771,
 2,
 array([[  26.46191434,  132.53808566],
        [ 498.94854843, 2499.05145157],
        [  53.58953722,  268.41046278]]))

(16.17275735040317,
 0.00030770203096045753,
 2,
 array([[  21.6220831 ,  109.3779169 ],
        [ 545.83380763, 2761.16619237],
        [  12.54410928,   63.45589072]]))

(11.992014385771508,
 0.0024886691410797327,
 2,
 array([[  84.47802198,  200.52197802],
        [ 374.37102371,  888.62897629],
        [ 566.15095431, 1343.84904569]]))

(2.3343059235586145,
 0.311251826863554,
 2,
 array([[ 310.34557548,  736.65442452],
        [ 160.95286293,  382.04713707],
        [ 553.7015616 , 1314.2984384 ]]))

(16.55692496741045,
 0.00025392731744019754,
 2,
 array([[ 531.47050318, 1261.52949682],
        [  97.2238288 ,  230.7761712 ],
        [ 396.30566802,  940.69433198]]))

(3.403852589402021,
 0.182331960464638,
 2,
 array([[  98.70589936,  234.29410064],
        [ 893.09572007, 2119.90427993],
        [  33.19838057,   78.80161943]]))

(6.896270943949977,
 0.03180488222237137,
 2,
 array([[ 159.17437825,  377.82562175],
        [ 776.90138809, 1844.09861191],
        [  88.92423366,  211.07576634]]))

(251.04685825062998,
 3.0610285574089815e-55,
 2,
 array([[  43.86928861,  104.13071139],
        [ 962.16020821, 2283.83979179],
        [  18.97050318,   45.02949682]]))

(261.4097211615027,
 1.720284561561009e-57,
 2,
 array([[ 116.19433198,  275.80566802],
        [ 854.26547137, 2027.73452863],
        [  54.54019665,  129.45980335]]))

(6.700042935007641,
 0.03508360093542364,
 2,
 array([[  16.93417573,   40.06582427],
        [ 976.24037614, 2309.75962386],
        [  17.82544813,   42.17455187]]))

(3.158832234991282,
 0.20609539857828285,
 2,
 array([[  32.63173217,   77.36826783],
        [ 838.33886463, 1987.66113537],
        [ 148.0294032 ,  350.9705968 ]]))

(0.35734300536811847,
 0.836380603058067,
 2,
 array([[  24.65260645,   63.34739355],
        [ 666.74094708, 1713.25905292],
        [  12.60644648,   32.39355352]]))

(7.585169397479487,
 0.022537274439359527,
 2,
 array([[  28.45825243,   67.54174757],
        [ 873.60906149, 2073.39093851],
        [  13.93268608,   33.06731392]]))

(12.932665365921297,
 0.0015549176655367113,
 2,
 array([[ 180.81260844,  429.18739156],
        [ 658.03932909, 1561.96067091],
        [ 186.14806246,  441.85193754]]))

(0.2671223209236662,
 0.8749739535300287,
 2,
 array([[  45.47682709,  111.52317291],
        [ 839.14884135, 2057.85115865],
        [  90.37433155,  221.62566845]]))

(60.29853103286175,
 8.060098566078528e-14,
 2,
 array([[  37.72462489,   91.27537511],
        [ 934.34245366, 2260.65754634],
        [  21.93292145,   53.06707855]]))

(14.773092370947904,
 0.000619532011272414,
 2,
 array([[ 191.68580406,   92.31419594],
        [ 861.23621822,  414.76378178],
        [1310.07797772,  630.92202228]]))

(8.812239660822828,
 0.01220243410413441,
 2,
 array([[ 708.697515  ,  341.302485  ],
        [ 371.89745787,  179.10254213],
        [1282.40502714,  617.59497286]]))

(79.77104329828799,
 4.7636302005438524e-18,
 2,
 array([[1223.00942588,  588.99057412],
        [ 225.43330477,  108.56669523],
        [ 914.55726935,  440.44273065]]))

(12.288129012690879,
 0.002146182693382987,
 2,
 array([[ 227.45815481,  109.54184519],
        [2060.6223936 ,  992.3776064 ],
        [  74.91945159,   36.08054841]]))

(3.3446760693709825,
 0.18780745158655163,
 2,
 array([[ 366.49785775,  176.50214225],
        [1790.64238789,  862.35761211],
        [ 205.85975436,   99.14024564]]))

(3.1050478191173916,
 0.2117129545908811,
 2,
 array([[  97.41052013,   46.58947987],
        [2161.29591537, 1033.70408463],
        [  43.2935645 ,   20.7064355 ]]))

(4.713385581415969,
 0.09473300757241553,
 2,
 array([[ 261.88060554,  126.11939446],
        [1977.60354185,  952.39645815],
        [ 123.51585261,   59.48414739]]))

(46.21827288238353,
 9.200884141208525e-11,
 2,
 array([[  39.82205084,   19.17794916],
        [2282.6809483 , 1099.3190517 ],
        [  40.49700086,   19.50299914]]))

(3.2396768209521785,
 0.19793068002400502,
 2,
 array([[  74.9544282,   36.0455718],
        [1935.3098309,  930.6901691],
        [ 345.7357409,  166.2642591]]))

(13.649650953513808,
 0.0010864655384081156,
 2,
 array([[  62.8742163 ,   32.1257837 ],
        [1595.68142633,  815.31857367],
        [  30.44435737,   15.55564263]]))

(0.8831075668519127,
 0.6430365049940434,
 2,
 array([[  62.93939394,   32.06060606],
        [1982.92216906, 1010.07783094],
        [  31.138437  ,   15.861563  ]]))

(0.744191032930428,
 0.6892884009882219,
 2,
 array([[ 417.11910883,  200.88089117],
        [1518.63753213,  731.36246787],
        [ 427.24335904,  205.75664096]]))

(9.552176308263416,
 0.008428907145257373,
 2,
 array([[ 105.00527241,   50.99472759],
        [1978.94551845,  961.05448155],
        [ 214.04920914,  103.95079086]]))

(10.451801143975059,
 0.0053755167396096985,
 2,
 array([[  86.87373004,   42.12626996],
        [2181.94484761, 1058.05515239],
        [  51.18142235,   24.81857765]]))

(1.9180206217020868,
 0.3832720184902962,
 2,
 array([[  85.94565525,  201.05434475],
        [ 385.40786867,  901.59213133],
        [ 586.64647608, 1372.35352392]]))

(21.86211321608767,
 1.7893794019683906e-05,
 2,
 array([[ 319.2267195 ,  746.7732805 ],
        [ 165.90206623,  388.09793377],
        [ 572.87121427, 1340.12878573]]))

(32.81390207140433,
 7.491205318272554e-08,
 2,
 array([[ 550.41154826, 1287.58845174],
        [  99.72091707,  233.27908293],
        [ 407.86753467,  954.13246533]]))

(0.9204823392744008,
 0.6311314174163032,
 2,
 array([[ 101.51769035,  237.48230965],
        [ 922.94254175, 2159.05745825],
        [  33.5397679 ,   78.4602321 ]]))

(7.346939449714332,
 0.0253882267839117,
 2,
 array([[ 164.40475517,  384.59524483],
        [ 801.66034532, 1875.33965468],
        [  91.93489952,  215.06510048]]))

(0.314647848886922,
 0.8544272441170531,
 2,
 array([[  43.52372635,  102.47627365],
        [ 961.39737991, 2263.60262009],
        [  19.07889374,   44.92110626]]))

(7.5963299161480515,
 0.022411860848920086,
 2,
 array([[ 117.38918766,  274.61081234],
        [ 885.50976507, 2071.49023493],
        [  55.10104727,  128.89895273]]))

(3.370973785306378,
 0.18535416240205133,
 2,
 array([[  17.35511608,   40.64488392],
        [1008.69131556, 2362.30868444],
        [  17.95356836,   42.04643164]]))

(247.90010576626085,
 1.4763046961032145e-54,
 2,
 array([[  34.43815454,   80.56184546],
        [ 869.03934333, 2032.96065667],
        [ 154.52250212,  361.47749788]]))

(3.5526929494705226,
 0.16925539788399807,
 2,
 array([[   4.85481998,   90.14518002],
        [ 124.79442509, 2317.20557491],
        [   2.35075494,   43.64924506]]))

(0.6187275899797662,
 0.7339137273178042,
 2,
 array([[  27.59165613,   69.40834387],
        [ 859.0391909 , 2160.9608091 ],
        [  13.36915297,   33.63084703]]))

(17.6388207630429,
 0.00014783550108280526,
 2,
 array([[ 185.96603453,  435.03396547],
        [ 681.87545995, 1595.12454005],
        [ 190.15850552,  444.84149448]]))

(14.675827016648018,
 0.0006504061732401911,
 2,
 array([[  47.2428115 ,  111.7571885 ],
        [ 880.97444089, 2084.02555911],
        [  94.7827476 ,  224.2172524 ]]))

(4.79902746747127,
 0.09076207709675942,
 2,
 array([[  38.61830743,   91.38169257],
        [ 971.10189983, 2297.89810017],
        [  22.27979275,   52.72020725]]))

(4.283940886915502,
 0.11742323906226396,
 2,
 array([[ 198.86178862,   11.13821138],
        [ 896.77197058,   50.22802942],
        [1350.36624081,   75.63375919]]))

(0.30913373296042057,
 0.8567861999491712,
 2,
 array([[ 699.80410376,   39.19589624],
        [ 369.31475029,   20.68524971],
        [1376.88114595,   77.11885405]]))

(0.6274883014531296,
 0.7307059548335173,
 2,
 array([[1204.53426249,   67.46573751],
        [ 222.53581107,   12.46418893],
        [1018.92992644,   57.07007356]]))

(4.8584079808104175,
 0.08810693864465044,
 2,
 array([[ 240.52806814,   13.47193186],
        [2120.24545103,  118.75454897],
        [  85.22648084,    4.77351916]]))

(0.43005396797569134,
 0.8065196767665411,
 2,
 array([[ 401.51142083,   22.48857917],
        [1816.27100271,  101.72899729],
        [ 228.21757646,   12.78242354]]))

(3.240058680258818,
 0.19789289279535274,
 2,
 array([[ 106.02785515,    5.97214485],
        [2222.7982491 ,  125.2017509 ],
        [  50.17389574,    2.82610426]]))

(0.9760228151442787,
 0.6138458705118258,
 2,
 array([[ 296.39876113,   16.60123887],
        [2031.2311266 ,  113.7688734 ],
        [ 118.37011227,    6.62988773]]))

(1.1671023205918083,
 0.5579136039072641,
 2,
 array([[  44.55054859,    2.44945141],
        [2324.21159875,  127.78840125],
        [  50.23785266,    2.76214734]]))

(17.178744732988527,
 0.0001860728365602395,
 2,
 array([[  86.17344173,    4.82655827],
        [1883.50522648,  105.49477352],
        [ 476.32133178,   26.67866822]]))

(83.74539842857665,
 6.530069279163155e-19,
 2,
 array([[  89.96128533,    5.03871467],
        [2312.47851336,  129.52148664],
        [  43.56020132,    2.43979868]]))

(8.533630813774746,
 0.014026380418050937,
 2,
 array([[7.00491525e+01, 3.95084746e+00],
        [2.12797966e+03, 1.20020339e+02],
        [3.59711864e+01, 2.02881356e+00]]))

(1.83089702819329,
 0.40033702901699675,
 2,
 array([[ 456.43515292,   25.56484708],
        [1509.4556717 ,   84.5443283 ],
        [ 480.10917538,   26.89082462]]))

(1.307240547579008,
 0.5201592450595895,
 2,
 array([[ 114.53069307,    6.46930693],
        [2029.37029703,  114.62970297],
        [ 246.0990099 ,   13.9009901 ]]))

(0.8444293447583072,
 0.6555932865155312,
 2,
 array([[  98.45333333,    5.54666667],
        [2259.69333333,  127.30666667],
        [  55.85333333,    3.14666667]]))

(11.270952115671543,
 0.0035689777888913573,
 2,
 array([[ 198.18639798,   25.81360202],
        [1128.95465995,  147.04534005],
        [1482.85894207,  193.14105793]]))

(4.602366352486718,
 0.10014028998953499,
 2,
 array([[ 870.60453401,  113.39546599],
        [ 452.1127204 ,   58.8872796 ],
        [1487.28274559,  193.71725441]]))

(2.302158421802486,
 0.3162952358523061,
 2,
 array([[1484.62846348,  193.37153652],
        [ 268.96725441,   35.03274559],
        [1056.40428212,  137.59571788]]))

(1.894412495221535,
 0.38782299278625876,
 2,
 array([[ 265.42821159,   34.57178841],
        [2458.75      ,  320.25      ],
        [  85.82178841,   11.17821159]]))

(0.24323587597530358,
 0.8854866146809172,
 2,
 array([[ 420.26133501,   54.73866499],
        [2160.58564232,  281.41435768],
        [ 229.15302267,   29.84697733]]))

(1.9795677529217377,
 0.37165700617025244,
 2,
 array([[ 114.01262136,   14.98737864],
        [2563.07443366,  336.92556634],
        [  53.91294498,    7.08705502]]))

(1.2731628233677652,
 0.5290981044434753,
 2,
 array([[ 314.97481108,   41.02518892],
        [2357.00251889,  306.99748111],
        [ 138.02267003,   17.97732997]]))

(1.8576289382864264,
 0.3950217433488569,
 2,
 array([[  47.74736842,    6.25263158],
        [2672.96842105,  350.03157895],
        [  51.28421053,    6.71578947]]))

(5.747989267065487,
 0.05647288691984129,
 2,
 array([[  93.73830594,   12.26169406],
        [2288.62958281,  299.37041719],
        [ 415.63211125,   54.36788875]]))

(5.632934295913271,
 0.05981689409604704,
 2,
 array([[  77.04661017,    9.95338983],
        [1973.10169492,  254.89830508],
        [  39.85169492,    5.14830508]]))

(54.823673715277444,
 1.2450606683027014e-12,
 2,
 array([[  85.82178841,   11.17821159],
        [2682.59445844,  349.40554156],
        [  41.58375315,    5.41624685]]))

(7.802600947910299,
 0.020215604476638404,
 2,
 array([[ 495.46599496,   64.53400504],
        [1811.98992443,  236.01007557],
        [ 502.5440806 ,   65.4559194 ]]))

(7.7304236366277195,
 0.020958482576406014,
 2,
 array([[ 125.70866903,   16.29133097],
        [2360.13599742,  305.86400258],
        [ 261.15533355,   33.84466645]]))

(2.5295508257557726,
 0.28230269057031077,
 2,
 array([[ 104.47877434,   13.52122566],
        [2612.85477178,  338.14522822],
        [  56.66645388,    7.33354612]]))

(2.682872608166483,
 0.6122149957897961,
 4,
 array([[ 47.34693878, 109.46938776, 127.18367347],
        [210.39379132, 486.44495545, 565.16125323],
        [322.25926991, 745.0856568 , 865.6550733 ]]))

(12.391308391316178,
 0.014666681302972048,
 4,
 array([[176.05058925, 407.04110377, 472.90830698],
        [ 91.19287151, 210.84420811, 244.96292038],
        [312.75653924, 723.11468813, 840.12877264]]))

(8.854186854109317,
 0.06484926404282151,
 4,
 array([[300.5863754 , 694.97643001, 807.4371946 ],
        [ 54.0155217 , 124.88761138, 145.09686692],
        [225.3981029 , 521.13595861, 605.46593849]]))

(0.9035579606014806,
 0.924049818278429,
 4,
 array([[  57.01638402,  131.82581201,  153.15780397],
        [ 504.47829836, 1166.38861742, 1355.13308422],
        [  18.50531762,   42.78557057,   49.70911181]]))

(2.089666360969624,
 0.7192710800145481,
 4,
 array([[  90.0258695 ,  208.14601897,  241.82811153],
        [ 438.45932739, 1013.74820351, 1177.7924691 ],
        [  51.5148031 ,  119.10577752,  138.37941937]]))

(14.859370386196836,
 0.005001958389049389,
 4,
 array([[  23.08377897,   54.19489008,   62.72133096],
        [ 521.5285205 , 1224.41740939, 1417.05407011],
        [  10.38770053,   24.38770053,   28.22459893]]))

(39.16551172835401,
 6.439033885223972e-08,
 4,
 array([[  64.85196896,  149.94222478,  174.20580627],
        [ 484.80597873, 1120.90485772, 1302.28916355],
        [  30.34205231,   70.15291751,   81.50503018]]))

(10.993084469631441,
 0.026641845416138045,
 4,
 array([[   9.41652021,   21.95518453,   25.62829525],
        [ 544.67135325, 1269.9340949 , 1482.39455185],
        [   9.91212654,   23.11072056,   26.9771529 ]]))

(11.596031353723903,
 0.020622245246424642,
 4,
 array([[  18.47313389,   42.81382515,   49.71304095],
        [ 470.64885274, 1090.78826605, 1266.56288121],
        [  83.87801336,  194.3979088 ,  225.72407784]]))

(2.5613842836256233,
 0.6336787389031779,
 4,
 array([[  13.66455446,   34.91643564,   44.4190099 ],
        [ 350.72356436,  896.18851485, 1140.08792079],
        [   6.61188119,   16.8950495 ,   21.49306931]]))

(3.9064729847341777,
 0.4188113046681249,
 4,
 array([[  15.35804061,   35.34128263,   41.30067676],
        [ 495.12987432, 1139.37222043, 1331.49790525],
        [   7.51208508,   17.28649694,   20.20141798]]))

(50.19673139620205,
 3.284971339616895e-10,
 4,
 array([[102.52946249, 237.05518827, 275.41534924],
        [370.77321069, 857.25323369, 995.97355562],
        [106.69732682, 246.69157804, 286.61109514]]))

(115.21091993038107,
 5.626064262276905e-24,
 4,
 array([[  26.50761713,   61.28743892,   71.20494395],
        [ 499.81029031, 1155.59586088, 1342.59384881],
        [  53.68209256,  124.1167002 ,  144.20120724]]))

(7.426656368922215,
 0.1149872639437568,
 4,
 array([[  21.31304348,   49.69304348,   57.99391304],
        [ 536.46086957, 1250.80086957, 1459.73826087],
        [  12.22608696,   28.50608696,   33.26782609]]))

(4.417885902734901,
 0.10981666874472387,
 2,
 array([[ 261.52817302,   28.47182698],
        [1149.82214001,  125.17785999],
        [1757.64968697,  191.35031303]]))

(5.182840020532511,
 0.0749135864587402,
 2,
 array([[ 956.83238475,  104.16761525],
        [ 498.70717131,   54.29282869],
        [1713.46044394,  186.53955606]]))

(17.624317005684993,
 0.000148911482930547,
 2,
 array([[1643.11838361,  178.88161639],
        [ 295.7973819 ,   32.2026181 ],
        [1230.08423449,  133.91576551]]))

(5.4226310052813105,
 0.06644933491738736,
 2,
 array([[ 307.52105862,   33.47894138],
        [2761.3767786 ,  300.6232214 ],
        [ 100.10216278,   10.89783722]]))

(8.7458809504392,
 0.012614094548857218,
 2,
 array([[ 488.78713717,   53.21286283],
        [2398.84462151,  261.15537849],
        [ 281.36824132,   30.63175868]]))

(25.24064119704498,
 3.3041853720991994e-06,
 2,
 array([[ 126.89585172,   14.10414828],
        [2876.30597234,  319.69402766],
        [  55.79817593,    6.20182407]]))

(54.43359798274195,
 1.513193206928809e-12,
 2,
 array([[ 349.90665908,   38.09334092],
        [2654.96186682,  289.03813318],
        [ 164.1314741 ,   17.8685259 ]]))

(0.7432245301772827,
 0.6896215810552337,
 2,
 array([[  52.29259797,    5.70740203],
        [2999.61161103,  327.38838897],
        [  54.095791  ,    5.904209  ]]))

(0.26968720379516475,
 0.8738525698849373,
 2,
 array([[ 101.81059298,   11.18940702],
        [2573.19516408,  282.80483592],
        [ 454.99424295,   50.00575705]]))

(2.0735299421654596,
 0.354599969596349,
 2,
 array([[  85.11607843,    8.88392157],
        [2183.13686275,  227.86313725],
        [  40.74705882,    4.25294118]]))

(7.778710859406649,
 0.020458528748834477,
 2,
 array([[  83.85732525,    9.14267475],
        [2698.76316629,  294.23683371],
        [  42.37950846,    4.62049154]]))

(3.984009331868455,
 0.13642167126728388,
 2,
 array([[ 562.73648264,   61.26351736],
        [2031.803358  ,  221.196642  ],
        [ 574.46015936,   62.53984064]]))

(5.816683414639642,
 0.054566141517047424,
 2,
 array([[ 141.84608696,   15.15391304],
        [2686.04086957,  286.95913043],
        [ 289.11304348,   30.88695652]]))

(43.99915742986391,
 2.7906435016979584e-10,
 2,
 array([[ 118.1385885 ,   12.8614115 ],
        [2982.32299374,  324.67700626],
        [  68.53841776,    7.46158224]]))

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Age Direction'],dfProfileLast_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Gender         Men  Women
Age Direction
Negative       143    179
No change       11   1495
Positive       515   1787

(518.8603210711149,
 2.1424605811048715e-113,
 2,
 array([[  52.15932203,  269.84067797],
        [ 243.95012107, 1262.04987893],
        [ 372.8905569 , 1929.1094431 ]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          1         0

Gender    Men  Women
Negative
0         526   3282
1         143    179

Chi2 value= 202.5052641992739
p-value= 5.931216108378838e-46
Degrees of freedom= 1

Gender     Men  Women
No change
0          658   1966
1           11   1495

Chi2 value= 415.9998641078357
p-value= 1.811894735455998e-92
Degrees of freedom= 1

Gender    Men  Women
Positive
0         154   1674
1         515   1787

Chi2 value= 144.98576250604805
p-value= 2.163085188797459e-33
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Weight Direction'],dfProfileLast_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Gender            Men  Women
Weight Direction
Negative          237   1919
No change          29    412
Positive          403   1130

(188.0944611187029,
 1.4315506872323344e-41,
 2,
 array([[ 349.24067797, 1806.75932203],
        [  71.43559322,  369.56440678],
        [ 248.32372881, 1284.67627119]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          0         1
4         0          0         1

Gender    Men  Women
Negative
0         432   1542
1         237   1919

Chi2 value= 89.25840811661553
p-value= 3.464672161504457e-21
Degrees of freedom= 1

Gender     Men  Women
No change
0          640   3049
1           29    412

Chi2 value= 32.888250755794374
p-value= 9.761142401353487e-09
Degrees of freedom= 1

Gender    Men  Women
Positive
0         266   2331
1         403   1130

Chi2 value= 181.65334906887162
p-value= 2.110746379212828e-41
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Smoking Direction'],dfProfileLast_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Smoking Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Gender             Men  Women
Smoking Direction
Negative            85    302
No change          557   3064
Positive            27     95

(14.415541064978106,
 0.000740806920692048,
 2,
 array([[  62.68837772,  324.31162228],
        [ 586.54939467, 3034.45060533],
        [  19.7622276 ,  102.2377724 ]]))

   Negative  No change  Positive
0         0          1         0
1         1          0         0
2         0          1         0
3         0          1         0
4         0          0         1

Gender    Men  Women
Negative
0         584   3159
1          85    302

Chi2 value= 9.992348723502515
p-value= 0.001571919827848069
Degrees of freedom= 1

Gender     Men  Women
No change
0          112    397
1          557   3064

Chi2 value= 13.929973969415474
p-value= 0.00018974835053964186
Degrees of freedom= 1

Gender    Men  Women
Positive
0         642   3366
1          27     95

Chi2 value= 2.824669022140415
p-value= 0.09282602635602884
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Alcohol Direction'],dfProfileLast_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Gender             Men  Women
Alcohol Direction
Negative           149    484
No change          395   2749
Positive           125    228

(151.71047514376318,
 1.138908670050192e-33,
 2,
 array([[ 102.53680387,  530.46319613],
        [ 509.28232446, 2634.71767554],
        [  57.18087167,  295.81912833]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Gender    Men  Women
Negative
0         520   2977
1         149    484

Chi2 value= 29.036451209430066
p-value= 7.102913267703498e-08
Degrees of freedom= 1

Gender     Men  Women
No change
0          274    712
1          395   2749

Chi2 value= 127.06109362351013
p-value= 1.801418564807427e-29
Degrees of freedom= 1

Gender    Men  Women
Positive
0         544   3233
1         125    228

Chi2 value= 103.41361397374342
p-value= 2.7199921723728037e-24
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Month Direction'],dfProfileLast_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Gender           Men  Women
Month Direction
Negative         135    257
No change        417   2612
Positive          42    142

(113.45088981535095,
 2.314473928893194e-25,
 2,
 array([[  64.59029126,  327.40970874],
        [ 499.09181692, 2529.90818308],
        [  30.31789182,  153.68210818]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Gender    Men  Women
Negative
0         534   3204
1         135    257

Chi2 value= 104.67296011294484
p-value= 1.4405355351936046e-24
Degrees of freedom= 1

Gender     Men  Women
No change
0          252    849
1          417   2612

Chi2 value= 48.82159279088129
p-value= 2.8033644431086893e-12
Degrees of freedom= 1

Gender    Men  Women
Positive
0         627   3319
1          42    142

Chi2 value= 5.730911590926353
p-value= 0.016668827709751612
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Children Direction'],dfProfileLast_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Children Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Gender              Men  Women
Children Direction
Negative             22     37
No change           524   2858
Positive             30     30

(70.02078111350683,
 6.239942272591712e-16,
 2,
 array([[   9.70694087,   49.29305913],
        [ 556.42159383, 2825.57840617],
        [   9.8714653 ,   50.1285347 ]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Gender    Men  Women
Negative
0         647   3424
1          22     37

Chi2 value= 18.06698977357248
p-value= 2.1326700424670716e-05
Degrees of freedom= 1

Gender     Men  Women
No change
0          145    603
1          524   2858

Chi2 value= 6.548742140059076
p-value= 0.01049583351856138
Degrees of freedom= 1

Gender    Men  Women
Positive
0         639   3431
1          30     30

Chi2 value= 48.749215278480186
p-value= 2.908749147088307e-12
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Direction'],dfProfileLast_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['STI Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Gender         Men  Women
STI Direction
Negative        50     65
No change      437   2465
Positive        91    425

(66.01061034500724,
 4.634235396481741e-15,
 2,
 array([[  18.81403906,   96.18596094],
        [ 474.76818568, 2427.23181432],
        [  84.41777526,  431.58222474]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Gender    Men  Women
Negative
0         619   3396
1          50     65

Chi2 value= 62.79995234326319
p-value= 2.2880437640558634e-15
Degrees of freedom= 1

Gender     Men  Women
No change
0          232    996
1          437   2465

Chi2 value= 9.06312315484615
p-value= 0.0026081610724401883
Degrees of freedom= 1

Gender    Men  Women
Positive
0         578   3036
1          91    425

Chi2 value= 0.7802455549918559
p-value= 0.37706605086881106
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Positive Direction'],dfProfileLast_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['STI Positive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Gender                  Men  Women
STI Positive Direction
Negative                 25     70
No change               385   2057
Positive                  5     41

(8.485416671587302,
 0.014368624039191754,
 2,
 array([[  15.26325978,   79.73674022],
        [ 392.34610918, 2049.65389082],
        [   7.39063105,   38.60936895]]))

   Negative  No change  Positive
0         0          0         0
1         0          0         0
2         0          0         0
3         0          0         0
4         0          0         0

Gender    Men  Women
Negative
0         644   3391
1          25     70

Chi2 value= 6.589062497819278
p-value= 0.010260719171468655
Degrees of freedom= 1

Gender     Men  Women
No change
0          284   1404
1          385   2057

Chi2 value= 0.7482312957625278
p-value= 0.3870367913839273
Degrees of freedom= 1

Gender    Men  Women
Positive
0         664   3420
1           5     41

Chi2 value= 0.616653329941817
p-value= 0.4322936550193811
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Frequency Direction'],dfProfileLast_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Gender                   Men  Women
Sex_Frequency Direction
Negative                 223    402
No change                252   2083
Positive                 119    526

(224.1213922470481,
 2.151087295586203e-49,
 2,
 array([[ 102.98196949,  522.01803051],
        [ 384.740638  , 1950.259362  ],
        [ 106.27739251,  538.72260749]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Gender    Men  Women
Negative
0         446   3059
1         223    402

Chi2 value= 204.21278838293676
p-value= 2.5150914473232797e-46
Degrees of freedom= 1

Gender     Men  Women
No change
0          417   1378
1          252   2083

Chi2 value= 114.76009937802111
p-value= 8.881787650947665e-27
Degrees of freedom= 1

Gender    Men  Women
Positive
0         550   2935
1         119    526

Chi2 value= 2.660216390570124
p-value= 0.10288673659064329
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Right_Time Direction'],dfProfileLast_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Gender                    Men  Women
Sex_Right_Time Direction
Negative                   37    122
No change                 475   2523
Positive                   67    255

(10.439418835967194,
 0.005408900627355771,
 2,
 array([[  26.46191434,  132.53808566],
        [ 498.94854843, 2499.05145157],
        [  53.58953722,  268.41046278]]))

   Negative  No change  Positive
0         0          0         0
1         0          0         0
2         0          0         0
3         0          1         0
4         0          1         0

Gender    Men  Women
Negative
0         632   3339
1          37    122

Chi2 value= 5.5626595568866035
p-value= 0.01834752078194738
Degrees of freedom= 1

Gender     Men  Women
No change
0          194    938
1          475   2523

Chi2 value= 0.9203922163090105
p-value= 0.33737201014610946
Degrees of freedom= 1

Gender    Men  Women
Positive
0         602   3206
1          67    255

Chi2 value= 5.10280524574984
p-value= 0.023887181800132593
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Contraception Direction'],dfProfileLast_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Gender                   Men  Women
Contraception Direction
Negative                  31    100
No change                526   2781
Positive                  23     53

(16.17275735040317,
 0.00030770203096045753,
 2,
 array([[  21.6220831 ,  109.3779169 ],
        [ 545.83380763, 2761.16619237],
        [  12.54410928,   63.45589072]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          1         0
4         0          1         0

Gender    Men  Women
Negative
0         638   3361
1          31    100

Chi2 value= 5.001342829118309
p-value= 0.02532766088850768
Degrees of freedom= 1

Gender     Men  Women
No change
0          143    680
1          526   2781

Chi2 value= 0.9432724904077412
p-value= 0.33143765947446907
Degrees of freedom= 1

Gender    Men  Women
Positive
0         646   3408
1          23     53

Chi2 value= 10.251728624611522
p-value= 0.0013655657897504116
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Age Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Trying_Conceive   No   Yes
Age Direction
Negative          98   187
No change        406   857
Positive         521  1389

(11.992014385771508,
 0.0024886691410797327,
 2,
 array([[  84.47802198,  200.52197802],
        [ 374.37102371,  888.62897629],
        [ 566.15095431, 1343.84904569]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          1         0

Trying_Conceive   No   Yes
Negative
0                927  2246
1                 98   187

Chi2 value= 3.1091951131270323
p-value= 0.07785142425415184
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                619  1576
1                406   857

Chi2 value= 5.795631905893097
p-value= 0.01606603940637824
Degrees of freedom= 1

Trying_Conceive   No   Yes
Positive
0                504  1044
1                521  1389

Chi2 value= 11.180627012571325
p-value= 0.0008265583511243934
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Weight Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Trying_Conceive    No   Yes
Weight Direction
Negative          586  1207
No change          88   240
Positive          351   986

(16.55692496741045,
 0.00025392731744019754,
 2,
 array([[ 531.47050318, 1261.52949682],
        [  97.2238288 ,  230.7761712 ],
        [ 396.30566802,  940.69433198]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          0         1
4         0          0         1

Trying_Conceive   No   Yes
Negative
0                439  1226
1                586  1207

Chi2 value= 16.21348264265223
p-value= 5.658992302649072e-05
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                937  2193
1                 88   240

Chi2 value= 1.2291505503523186
p-value= 0.267572299415764
Degrees of freedom= 1

Trying_Conceive   No   Yes
Positive
0                674  1447
1                351   986

Chi2 value= 11.73823581696378
p-value= 0.0006122903582139592
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Alcohol Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Trying_Conceive     No   Yes
Alcohol Direction
Negative           176   361
No change          747  1874
Positive           102   198

(6.896270943949977,
 0.03180488222237137,
 2,
 array([[ 159.17437825,  377.82562175],
        [ 776.90138809, 1844.09861191],
        [  88.92423366,  211.07576634]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Trying_Conceive   No   Yes
Negative
0                849  2072
1                176   361

Chi2 value= 2.8173617219822287
p-value= 0.09324956114181593
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                278   559
1                747  1874

Chi2 value= 6.533594587246597
p-value= 0.010585582523617736
Degrees of freedom= 1

Trying_Conceive   No   Yes
Positive
0                923  2235
1                102   198

Chi2 value= 2.7678626229594796
p-value= 0.09617450345267667
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Conceive Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Conceive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Trying_Conceive      No   Yes
Conceive Direction
Negative            129    19
No change           870  2376
Positive             26    38

(251.04685825062998,
 3.0610285574089815e-55,
 2,
 array([[  43.86928861,  104.13071139],
        [ 962.16020821, 2283.83979179],
        [  18.97050318,   45.02949682]]))

   Negative  No change  Positive
0         0          0         0
1         1          0         0
2         0          0         0
3         0          0         0
4         0          1         0

Trying_Conceive   No   Yes
Negative
0                896  2414
1                129    19

Chi2 value= 242.42380659351818
p-value= 1.1647114015330291e-54
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                155    57
1                870  2376

Chi2 value= 202.43532300052755
p-value= 6.143354465436727e-46
Degrees of freedom= 1

Trying_Conceive   No   Yes
Positive
0                999  2395
1                 26    38

Chi2 value= 3.2544425526904432
p-value= 0.07123015325742463
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Month Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Trying_Conceive    No   Yes
Month Direction
Negative            8   384
No change        1016  1866
Positive            1   183

(261.4097211615027,
 1.720284561561009e-57,
 2,
 array([[ 116.19433198,  275.80566802],
        [ 854.26547137, 2027.73452863],
        [  54.54019665,  129.45980335]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Trying_Conceive    No   Yes
Negative
0                1017  2049
1                   8   384

Chi2 value= 160.00607368854037
p-value= 1.1280317118873021e-36
Degrees of freedom= 1

Trying_Conceive    No   Yes
No change
0                   9   567
1                1016  1866

Chi2 value= 259.6621430766406
p-value= 2.0331108716737114e-58
Degrees of freedom= 1

Trying_Conceive    No   Yes
Positive
0                1024  2250
1                   1   183

Chi2 value= 77.43240448379224
p-value= 1.3734330824419635e-18
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Children Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Children Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Trying_Conceive      No   Yes
Children Direction
Negative              9    48
No change           980  2306
Positive             22    38

(6.700042935007641,
 0.03508360093542364,
 2,
 array([[  16.93417573,   40.06582427],
        [ 976.24037614, 2309.75962386],
        [  17.82544813,   42.17455187]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Trying_Conceive    No   Yes
Negative
0                1016  2385
1                   9    48

Chi2 value= 4.678157602723793
p-value= 0.030548494894045347
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                 45   127
1                980  2306

Chi2 value= 0.8820343223926951
p-value= 0.3476450997300107
Degrees of freedom= 1

Trying_Conceive    No   Yes
Positive
0                1003  2395
1                  22    38

Chi2 value= 1.1225038466593813
p-value= 0.2893799491426964
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Menstrual_Information Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Menstrual_Information Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Trying_Conceive                   No   Yes
Menstrual_Information Direction
Negative                          39    57
No change                        859  2088
Positive                          18    29

(7.585169397479487,
 0.022537274439359527,
 2,
 array([[  28.45825243,   67.54174757],
        [ 873.60906149, 2073.39093851],
        [  13.93268608,   33.06731392]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Trying_Conceive   No   Yes
Negative
0                986  2376
1                 39    57

Chi2 value= 5.182921906045566
p-value= 0.022809934565453945
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                166   345
1                859  2088

Chi2 value= 2.1680593501376118
p-value= 0.1409039496690174
Degrees of freedom= 1

Trying_Conceive    No   Yes
Positive
0                1007  2404
1                  18    29

Chi2 value= 1.317072726637482
p-value= 0.251118081180862
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Frequency Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Trying_Conceive           No   Yes
Sex_Frequency Direction
Negative                 180   430
No change                695  1525
Positive                 150   478

(12.932665365921297,
 0.0015549176655367113,
 2,
 array([[ 180.81260844,  429.18739156],
        [ 658.03932909, 1561.96067091],
        [ 186.14806246,  441.85193754]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Trying_Conceive   No   Yes
Negative
0                845  2003
1                180   430

Chi2 value= 0.0009326970057559854
p-value= 0.9756363222785029
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                330   908
1                695  1525

Chi2 value= 8.020190517062753
p-value= 0.004625870388290719
Degrees of freedom= 1

Trying_Conceive   No   Yes
Positive
0                875  1955
1                150   478

Chi2 value= 11.855906715000287
p-value= 0.0005747874313495607
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Contraception Direction'],dfProfileLast_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Trying_Conceive           No   Yes
Contraception Direction
Negative                  72    57
No change                886  2309
Positive                  36    39

(60.29853103286175,
 8.060098566078528e-14,
 2,
 array([[  37.72462489,   91.27537511],
        [ 934.34245366, 2260.65754634],
        [  21.93292145,   53.06707855]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          1         0
4         0          1         0

Trying_Conceive   No   Yes
Negative
0                953  2376
1                 72    57

Chi2 value= 42.71863221688029
p-value= 6.320735989470612e-11
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                139   124
1                886  2309

Chi2 value= 72.3288442125074
p-value= 1.8216524495704982e-17
Degrees of freedom= 1

Trying_Conceive   No   Yes
Positive
0                989  2394
1                 36    39

Chi2 value= 11.505839077420038
p-value= 0.0006937790527466873
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Age Direction'],dfProfileLast_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Previous_Children    No  Yes
Age Direction
Negative            216   68
No change           879  397
Positive           1268  673

(14.773092370947904,
 0.000619532011272414,
 2,
 array([[ 191.68580406,   92.31419594],
        [ 861.23621822,  414.76378178],
        [1310.07797772,  630.92202228]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          1         0

Previous_Children    No   Yes
Negative
0                  2147  1070
1                   216    68

Chi2 value= 9.905417679220081
p-value= 0.001647929236514932
Degrees of freedom= 1

Previous_Children    No  Yes
No change
0                  1484  741
1                   879  397

Chi2 value= 1.675180211785717
p-value= 0.19556612197795692
Degrees of freedom= 1

Previous_Children    No  Yes
Positive
0                  1095  465
1                  1268  673

Chi2 value= 9.110599157679069
p-value= 0.00254132618065326
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Height Direction'],dfProfileLast_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Previous_Children    No  Yes
Height Direction
Negative            717  333
No change           342  209
Positive           1304  596

(8.812239660822828,
 0.01220243410413441,
 2,
 array([[ 708.697515  ,  341.302485  ],
        [ 371.89745787,  179.10254213],
        [1282.40502714,  617.59497286]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          0         1

Previous_Children    No  Yes
Negative
0                  1646  805
1                   717  333

Chi2 value= 0.37748841134419686
p-value= 0.5389504705416757
Degrees of freedom= 1

Previous_Children    No  Yes
No change
0                  2021  929
1                   342  209

Chi2 value= 8.484305284793786
p-value= 0.003582233463009745
Degrees of freedom= 1

Previous_Children    No  Yes
Positive
0                  1059  542
1                  1304  596

Chi2 value= 2.3344434495333726
p-value= 0.1265402092272404
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Weight Direction'],dfProfileLast_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Previous_Children    No  Yes
Weight Direction
Negative           1345  467
No change           190  144
Positive            828  527

(79.77104329828799,
 4.7636302005438524e-18,
 2,
 array([[1223.00942588,  588.99057412],
        [ 225.43330477,  108.56669523],
        [ 914.55726935,  440.44273065]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          0         1
4         0          0         1

Previous_Children    No  Yes
Negative
0                  1018  671
1                  1345  467

Chi2 value= 76.96046347561196
p-value= 1.744148146591083e-18
Degrees of freedom= 1

Previous_Children    No  Yes
No change
0                  2173  994
1                   190  144

Chi2 value= 18.41005831129855
p-value= 1.7811529766436736e-05
Degrees of freedom= 1

Previous_Children    No  Yes
Positive
0                  1535  611
1                   828  527

Chi2 value= 40.64212982968391
p-value= 1.8282210381549237e-10
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Smoking Direction'],dfProfileLast_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Smoking Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Previous_Children    No  Yes
Smoking Direction
Negative            226  111
No change          2079  974
Positive             58   53

(12.288129012690879,
 0.002146182693382987,
 2,
 array([[ 227.45815481,  109.54184519],
        [2060.6223936 ,  992.3776064 ],
        [  74.91945159,   36.08054841]]))

   Negative  No change  Positive
0         0          1         0
1         1          0         0
2         0          1         0
3         0          1         0
4         0          0         1

Previous_Children    No   Yes
Negative
0                  2137  1027
1                   226   111

Chi2 value= 0.013739639687450584
p-value= 0.9066887224204294
Degrees of freedom= 1

Previous_Children    No  Yes
No change
0                   284  164
1                  2079  974

Chi2 value= 3.728930363497451
p-value= 0.05347762948521957
Degrees of freedom= 1

Previous_Children    No   Yes
Positive
0                  2305  1085
1                    58    53

Chi2 value= 11.433125389742202
p-value= 0.0007214622688400595
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Children Direction'],dfProfileLast_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Children Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Previous_Children     No   Yes
Children Direction
Negative              56     3
No change           2285  1097
Positive              22    38

(46.21827288238353,
 9.200884141208525e-11,
 2,
 array([[  39.82205084,   19.17794916],
        [2282.6809483 , 1099.3190517 ],
        [  40.49700086,   19.50299914]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Previous_Children    No   Yes
Negative
0                  2307  1135
1                    56     3

Chi2 value= 19.314611383463934
p-value= 1.108547931934517e-05
Degrees of freedom= 1

Previous_Children    No   Yes
No change
0                    78    41
1                  2285  1097

Chi2 value= 0.13120182277993012
p-value= 0.7171891880368275
Degrees of freedom= 1

Previous_Children    No   Yes
Positive
0                  2341  1100
1                    22    38

Chi2 value= 25.03425664913988
p-value= 5.632073241081369e-07
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Positive Direction'],dfProfileLast_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['STI Positive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Previous_Children         No  Yes
STI Positive Direction
Negative                  74   21
No change               1576  835
Positive                  39    7

(13.649650953513808,
 0.0010864655384081156,
 2,
 array([[  62.8742163 ,   32.1257837 ],
        [1595.68142633,  815.31857367],
        [  30.44435737,   15.55564263]]))

   Negative  No change  Positive
0         0          0         0
1         0          0         0
2         0          0         0
3         0          0         0
4         0          0         0

Previous_Children    No   Yes
Negative
0                  2289  1117
1                    74    21

Chi2 value= 4.338948550520186
p-value= 0.03724992063085946
Degrees of freedom= 1

Previous_Children    No  Yes
No change
0                   787  303
1                  1576  835

Chi2 value= 15.672949607816117
p-value= 7.529334822308691e-05
Degrees of freedom= 1

Previous_Children    No   Yes
Positive
0                  2324  1131
1                    39     7

Chi2 value= 5.576286099009462
p-value= 0.018205289786726555
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Right_Time Direction'],dfProfileLast_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Previous_Children           No  Yes
Sex_Right_Time Direction
Negative                   121   35
No change                 1975  965
Positive                   202  116

(9.552176308263416,
 0.008428907145257373,
 2,
 array([[ 105.00527241,   50.99472759],
        [1978.94551845,  961.05448155],
        [ 214.04920914,  103.95079086]]))

   Negative  No change  Positive
0         0          0         0
1         0          0         0
2         0          0         0
3         0          1         0
4         0          1         0

Previous_Children    No   Yes
Negative
0                  2242  1103
1                   121    35

Chi2 value= 7.072651934769617
p-value= 0.007826932344534701
Degrees of freedom= 1

Previous_Children    No  Yes
No change
0                   388  173
1                  1975  965

Chi2 value= 0.7583072442601692
p-value= 0.38385878589505973
Degrees of freedom= 1

Previous_Children    No   Yes
Positive
0                  2161  1022
1                   202   116

Chi2 value= 2.3212507367374364
p-value= 0.1276173768103067
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Contraception Direction'],dfProfileLast_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Previous_Children          No   Yes
Contraception Direction
Negative                   99    30
No change                2161  1079
Positive                   60    16

(10.451801143975059,
 0.0053755167396096985,
 2,
 array([[  86.87373004,   42.12626996],
        [2181.94484761, 1058.05515239],
        [  51.18142235,   24.81857765]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          1         0
4         0          1         0

Previous_Children    No   Yes
Negative
0                  2264  1108
1                    99    30

Chi2 value= 4.79397289947595
p-value= 0.028559479849777573
Degrees of freedom= 1

Previous_Children    No   Yes
No change
0                   202    59
1                  2161  1079

Chi2 value= 12.115213751536444
p-value= 0.0005001210494560276
Degrees of freedom= 1

Previous_Children    No   Yes
Positive
0                  2303  1122
1                    60    16

Chi2 value= 4.125971216591673
p-value= 0.04222977405652184
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Height Direction'],dfProfileLast_DiffLast['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

STI_Tested         No   Yes
Height Direction
Negative          366   700
No change         182   372
Positive          510  1403

(21.86211321608767,
 1.7893794019683906e-05,
 2,
 array([[ 319.2267195 ,  746.7732805 ],
        [ 165.90206623,  388.09793377],
        [ 572.87121427, 1340.12878573]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          0         1

STI_Tested   No   Yes
Negative
0           692  1775
1           366   700

Chi2 value= 13.712109290821285
p-value= 0.00021307619399269393
Degrees of freedom= 1

STI_Tested   No   Yes
No change
0           876  2103
1           182   372

Chi2 value= 2.4826981302763693
p-value= 0.11510464186301432
Degrees of freedom= 1

STI_Tested   No   Yes
Positive
0           548  1072
1           510  1403

Chi2 value= 21.140169009278953
p-value= 4.268855256814368e-06
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Weight Direction'],dfProfileLast_DiffLast['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

STI_Tested         No   Yes
Weight Direction
Negative          616  1222
No change         110   223
Positive          332  1030

(32.81390207140433,
 7.491205318272554e-08,
 2,
 array([[ 550.41154826, 1287.58845174],
        [  99.72091707,  233.27908293],
        [ 407.86753467,  954.13246533]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          0         1
4         0          0         1

STI_Tested   No   Yes
Negative
0           442  1253
1           616  1222

Chi2 value= 22.901435945829757
p-value= 1.705244167056538e-06
Degrees of freedom= 1

STI_Tested   No   Yes
No change
0           948  2252
1           110   223

Chi2 value= 1.511374491089465
p-value= 0.21892947097692506
Degrees of freedom= 1

STI_Tested   No   Yes
Positive
0           726  1445
1           332  1030

Chi2 value= 32.35204434024375
p-value= 1.2862182030067052e-08
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Alcohol Direction'],dfProfileLast_DiffLast['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

STI_Tested          No   Yes
Alcohol Direction
Negative           142   407
No change          833  1844
Positive            83   224

(7.346939449714332,
 0.0253882267839117,
 2,
 array([[ 164.40475517,  384.59524483],
        [ 801.66034532, 1875.33965468],
        [  91.93489952,  215.06510048]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

STI_Tested   No   Yes
Negative
0           916  2068
1           142   407

Chi2 value= 4.932597571297348
p-value= 0.026354673428957878
Degrees of freedom= 1

STI_Tested   No   Yes
No change
0           225   631
1           833  1844

Chi2 value= 6.989834912171192
p-value= 0.008197391419452141
Degrees of freedom= 1

STI_Tested   No   Yes
Positive
0           975  2251
1            83   224

Chi2 value= 1.209837744809366
p-value= 0.27136425849777945
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Month Direction'],dfProfileLast_DiffLast['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

STI_Tested        No   Yes
Month Direction
Negative         101   291
No change        889  2068
Positive          68   116

(7.5963299161480515,
 0.022411860848920086,
 2,
 array([[ 117.38918766,  274.61081234],
        [ 885.50976507, 2071.49023493],
        [  55.10104727,  128.89895273]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

STI_Tested   No   Yes
Negative
0           957  2184
1           101   291

Chi2 value= 3.453181666648188
p-value= 0.06313013670116549
Degrees of freedom= 1

STI_Tested   No   Yes
No change
0           169   407
1           889  2068

Chi2 value= 0.08841111208644035
p-value= 0.7662068993487823
Degrees of freedom= 1

STI_Tested   No   Yes
Positive
0           990  2359
1            68   116

Chi2 value= 4.201526232834805
p-value= 0.0403876144150185
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Direction'],dfProfileLast_DiffLast['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['STI Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

STI_Tested      No   Yes
STI Direction
Negative        68    47
No change      976  1926
Positive        14   502

(247.90010576626085,
 1.4763046961032145e-54,
 2,
 array([[  34.43815454,   80.56184546],
        [ 869.03934333, 2032.96065667],
        [ 154.52250212,  361.47749788]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

STI_Tested   No   Yes
Negative
0           990  2428
1            68    47

Chi2 value= 46.83325311167904
p-value= 7.729075540152725e-12
Degrees of freedom= 1

STI_Tested   No   Yes
No change
0            82   549
1           976  1926

Chi2 value= 104.2369163855842
p-value= 1.7951451253525508e-24
Degrees of freedom= 1

STI_Tested    No   Yes
Positive
0           1044  1973
1             14   502

Chi2 value= 212.1000141534971
p-value= 4.783137131270849e-48
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Frequency Direction'],dfProfileLast_DiffLast['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

STI_Tested                No   Yes
Sex_Frequency Direction
Negative                 180   441
No change                729  1548
Positive                 149   486

(17.6388207630429,
 0.00014783550108280526,
 2,
 array([[ 185.96603453,  435.03396547],
        [ 681.87545995, 1595.12454005],
        [ 190.15850552,  444.84149448]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

STI_Tested   No   Yes
Negative
0           878  2034
1           180   441

Chi2 value= 0.2782478469774265
p-value= 0.597851946173692
Degrees of freedom= 1

STI_Tested   No   Yes
No change
0           329   927
1           729  1548

Chi2 value= 12.801076483683582
p-value= 0.0003464199618359407
Degrees of freedom= 1

STI_Tested   No   Yes
Positive
0           909  1989
1           149   486

Chi2 value= 15.128670268132385
p-value= 0.00010042649565385397
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Right_Time Direction'],dfProfileLast_DiffLast['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

STI_Tested                 No   Yes
Sex_Right_Time Direction
Negative                   49   110
No change                 909  2056
Positive                   65   254

(14.675827016648018,
 0.0006504061732401911,
 2,
 array([[  47.2428115 ,  111.7571885 ],
        [ 880.97444089, 2084.02555911],
        [  94.7827476 ,  224.2172524 ]]))

   Negative  No change  Positive
0         0          0         0
1         0          0         0
2         0          0         0
3         0          1         0
4         0          1         0

STI_Tested    No   Yes
Negative
0           1009  2365
1             49   110

Chi2 value= 0.0246157392305837
p-value= 0.8753283584768786
Degrees of freedom= 1

STI_Tested   No   Yes
No change
0           149   419
1           909  2056

Chi2 value= 4.241320412548876
p-value= 0.039451472896847306
Degrees of freedom= 1

STI_Tested   No   Yes
Positive
0           993  2221
1            65   254

Chi2 value= 14.811505474796999
p-value= 0.0001188084393958671
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Direction'],dfProfileLast_DiffLast['STI_Positive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['STI Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['STI_Positive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

STI_Positive     No  Yes
STI Direction
Negative         85    6
No change      1866  123
Positive        495    8

(17.178744732988527,
 0.0001860728365602395,
 2,
 array([[  86.17344173,    4.82655827],
        [1883.50522648,  105.49477352],
        [ 476.32133178,   26.67866822]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

STI_Positive    No  Yes
Negative
0             2361  131
1               85    6

Chi2 value= 0.10285059824558776
p-value= 0.7484352561565122
Degrees of freedom= 1

STI_Positive    No  Yes
No change
0              580   14
1             1866  123

Chi2 value= 12.58750949930872
p-value= 0.00038833326490808395
Degrees of freedom= 1

STI_Positive    No  Yes
Positive
0             1951  129
1              495    8

Chi2 value= 16.243851299075438
p-value= 5.569003453702192e-05
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Positive Direction'],dfProfileLast_DiffLast['STI_Positive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['STI Positive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['STI_Positive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

STI_Positive              No  Yes
STI Positive Direction
Negative                  94    1
No change               2322  120
Positive                  30   16

(83.74539842857665,
 6.530069279163155e-19,
 2,
 array([[  89.96128533,    5.03871467],
        [2312.47851336,  129.52148664],
        [  43.56020132,    2.43979868]]))

   Negative  No change  Positive
0         0          0         0
1         0          0         0
2         0          0         0
3         0          0         0
4         0          0         0

STI_Positive    No  Yes
Negative
0             2352  136
1               94    1

Chi2 value= 2.724666242112656
p-value= 0.09880877446747535
Degrees of freedom= 1

STI_Positive    No  Yes
No change
0              124   17
1             2322  120

Chi2 value= 12.155914796315805
p-value= 0.0004893243697354331
Degrees of freedom= 1

STI_Positive    No  Yes
Positive
0             2416  121
1               30   16

Chi2 value= 75.16534282470803
p-value= 4.328996211809919e-18
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Menstrual_Information Direction'],dfProfileLast_DiffLast['STI_Positive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Menstrual_Information Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['STI_Positive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

STI_Positive                       No  Yes
Menstrual_Information Direction
Negative                           71    3
No change                        2131  117
Positive                           32    6

(8.533630813774746,
 0.014026380418050937,
 2,
 array([[7.00491525e+01, 3.95084746e+00],
        [2.12797966e+03, 1.20020339e+02],
        [3.59711864e+01, 2.02881356e+00]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

STI_Positive    No  Yes
Negative
0             2375  134
1               71    3

Chi2 value= 0.050006224132498514
p-value= 0.823052443661276
Degrees of freedom= 1

STI_Positive    No  Yes
No change
0              315   20
1             2131  117

Chi2 value= 0.2048335801169704
p-value= 0.6508472853497128
Degrees of freedom= 1

STI_Positive    No  Yes
Positive
0             2414  131
1               32    6

Chi2 value= 6.45668018836331
p-value= 0.011053597001310393
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Age Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Menstrual_Information    No  Yes
Age Direction
Negative                183   41
No change              1141  135
Positive               1486  190

(11.270952115671543,
 0.0035689777888913573,
 2,
 array([[ 198.18639798,   25.81360202],
        [1128.95465995,  147.04534005],
        [1482.85894207,  193.14105793]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          1         0

Menstrual_Information    No  Yes
Negative
0                      2627  325
1                       183   41

Chi2 value= 10.160621894268898
p-value= 0.0014347221625681788
Degrees of freedom= 1

Menstrual_Information    No  Yes
No change
0                      1669  231
1                      1141  135

Chi2 value= 1.712628861204417
p-value= 0.19064464415851892
Degrees of freedom= 1

Menstrual_Information    No  Yes
Positive
0                      1324  176
1                      1486  190

Chi2 value= 0.08642604883627655
p-value= 0.7687708358228798
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Menstrual_Information Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Menstrual_Information Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Menstrual_Information              No  Yes
Menstrual_Information Direction
Negative                           92    5
No change                        2692  340
Positive                           26   21

(54.823673715277444,
 1.2450606683027014e-12,
 2,
 array([[  85.82178841,   11.17821159],
        [2682.59445844,  349.40554156],
        [  41.58375315,    5.41624685]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Menstrual_Information    No  Yes
Negative
0                      2718  361
1                        92    5

Chi2 value= 3.3627594046938762
p-value= 0.06668623999721505
Degrees of freedom= 1

Menstrual_Information    No  Yes
No change
0                       118   26
1                      2692  340

Chi2 value= 5.658262044277895
p-value= 0.01737333018076563
Degrees of freedom= 1

Menstrual_Information    No  Yes
Positive
0                      2784  345
1                        26   21

Chi2 value= 48.19139385019417
p-value= 3.86581331218634e-12
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Frequency Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Menstrual_Information      No  Yes
Sex_Frequency Direction
Negative                  480   80
No change                1813  235
Positive                  517   51

(7.802600947910299,
 0.020215604476638404,
 2,
 array([[ 495.46599496,   64.53400504],
        [1811.98992443,  236.01007557],
        [ 502.5440806 ,   65.4559194 ]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Menstrual_Information    No  Yes
Negative
0                      2330  286
1                       480   80

Chi2 value= 4.762549457383871
p-value= 0.02908543604056465
Degrees of freedom= 1

Menstrual_Information    No  Yes
No change
0                       997  131
1                      1813  235

Chi2 value= 0.003508197749237543
p-value= 0.9527688824316799
Degrees of freedom= 1

Menstrual_Information    No  Yes
Positive
0                      2293  315
1                       517   51

Chi2 value= 4.095576648036943
p-value= 0.04299556105558112
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Right_Time Direction'],dfProfileLast_DiffLast['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Menstrual_Information       No  Yes
Sex_Right_Time Direction
Negative                   122   20
No change                 2350  316
Positive                   275   20

(7.7304236366277195,
 0.020958482576406014,
 2,
 array([[ 125.70866903,   16.29133097],
        [2360.13599742,  305.86400258],
        [ 261.15533355,   33.84466645]]))

   Negative  No change  Positive
0         0          0         0
1         0          0         0
2         0          0         0
3         0          1         0
4         0          1         0

Menstrual_Information    No  Yes
Negative
0                      2688  346
1                       122   20

Chi2 value= 0.7110626130359219
p-value= 0.3990912756835818
Degrees of freedom= 1

Menstrual_Information    No  Yes
No change
0                       460   50
1                      2350  316

Chi2 value= 1.5676497522465245
p-value= 0.21054865517249402
Degrees of freedom= 1

Menstrual_Information    No  Yes
Positive
0                      2535  346
1                       275   20

Chi2 value= 6.675329045002194
p-value= 0.009775646381007948
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Height Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Sex_Right_Time     No  Unsure  Yes
Height Direction
Negative          193     402  461
No change         110     210  227
Positive          277     729  870

(12.391308391316178,
 0.014666681302972048,
 4,
 array([[176.05058925, 407.04110377, 472.90830698],
        [ 91.19287151, 210.84420811, 244.96292038],
        [312.75653924, 723.11468813, 840.12877264]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          0         1

Sex_Right_Time   No  Unsure   Yes
Negative
0               387     939  1097
1               193     402   461

Chi2 value= 2.86319546819461
p-value= 0.2389268755047199
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
No change
0               470    1131  1331
1               110     210   227

Chi2 value= 6.169252952284891
p-value= 0.0457471183494128
Degrees of freedom= 2

Sex_Right_Time   No  Unsure  Yes
Positive
0               303     612  688
1               277     729  870

Chi2 value= 11.281091464662582
p-value= 0.0035509300200313792
Degrees of freedom= 2

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Conceive Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Conceive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Sex_Right_Time       No  Unsure   Yes
Conceive Direction
Negative             33      57    50
No change           504    1223  1436
Positive             18      23    22

(14.859370386196836,
 0.005001958389049389,
 4,
 array([[  23.08377897,   54.19489008,   62.72133096],
        [ 521.5285205 , 1224.41740939, 1417.05407011],
        [  10.38770053,   24.38770053,   28.22459893]]))

   Negative  No change  Positive
0         0          0         0
1         1          0         0
2         0          0         0
3         0          0         0
4         0          1         0

Sex_Right_Time   No  Unsure   Yes
Negative
0               547    1284  1508
1                33      57    50

Chi2 value= 7.022499304569667
p-value= 0.02985957702374152
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
No change
0                76     118   122
1               504    1223  1436

Chi2 value= 14.442752178136493
p-value= 0.0007307960861322829
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
Positive
0               562    1318  1536
1                18      23    22

Chi2 value= 6.912654553447391
p-value= 0.03154540707304969
Degrees of freedom= 2

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Month Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Sex_Right_Time    No  Unsure   Yes
Month Direction
Negative          47     119   223
No change        515    1155  1238
Positive          18      67    97

(39.16551172835401,
 6.439033885223972e-08,
 4,
 array([[  64.85196896,  149.94222478,  174.20580627],
        [ 484.80597873, 1120.90485772, 1302.28916355],
        [  30.34205231,   70.15291751,   81.50503018]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Sex_Right_Time   No  Unsure   Yes
Negative
0               533    1222  1335
1                47     119   223

Chi2 value= 28.10946471094383
p-value= 7.872402550809637e-07
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
No change
0                65     186   320
1               515    1155  1238

Chi2 value= 37.113244843643315
p-value= 8.728935400153224e-09
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
Positive
0               562    1274  1461
1                18      67    97

Chi2 value= 8.555325004672984
p-value= 0.013875057123675
Degrees of freedom= 2

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Children Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Children Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Sex_Right_Time       No  Unsure   Yes
Children Direction
Negative              7      15    35
No change           550    1282  1465
Positive              7      18    35

(10.993084469631441,
 0.026641845416138045,
 4,
 array([[   9.41652021,   21.95518453,   25.62829525],
        [ 544.67135325, 1269.9340949 , 1482.39455185],
        [   9.91212654,   23.11072056,   26.9771529 ]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Sex_Right_Time   No  Unsure   Yes
Negative
0               573    1326  1523
1                 7      15    35

Chi2 value= 6.493304700042219
p-value= 0.038904227817026696
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
No change
0                30      59    93
1               550    1282  1465

Chi2 value= 3.5857104286766344
p-value= 0.16648414249986704
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
Positive
0               573    1323  1523
1                 7      18    35

Chi2 value= 4.577160374003646
p-value= 0.10141034341098489
Degrees of freedom= 2

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['STI Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['STI Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Sex_Right_Time   No  Unsure   Yes
STI Direction
Negative         19      41    51
No change       484    1113  1231
Positive         70     174   260

(11.596031353723903,
 0.020622245246424642,
 4,
 array([[  18.47313389,   42.81382515,   49.71304095],
        [ 470.64885274, 1090.78826605, 1266.56288121],
        [  83.87801336,  194.3979088 ,  225.72407784]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Sex_Right_Time   No  Unsure   Yes
Negative
0               561    1300  1507
1                19      41    51

Chi2 value= 0.12526043170644666
p-value= 0.9392907443040498
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
No change
0                96     228   327
1               484    1113  1231

Chi2 value= 9.664692130659532
p-value= 0.007967806327126528
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
Positive
0               510    1167  1298
1                70     174   260

Chi2 value= 11.303751529656314
p-value= 0.0035109249249762105
Degrees of freedom= 2

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Frequency Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Sex_Right_Time            No  Unsure  Yes
Sex_Frequency Direction
Negative                  99     235  281
No change                421     879  924
Positive                  60     227  353

(50.19673139620205,
 3.284971339616895e-10,
 4,
 array([[102.52946249, 237.05518827, 275.41534924],
        [370.77321069, 857.25323369, 995.97355562],
        [106.69732682, 246.69157804, 286.61109514]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Sex_Right_Time   No  Unsure   Yes
Negative
0               481    1106  1277
1                99     235   281

Chi2 value= 0.306789313982863
p-value= 0.8577911217369639
Degrees of freedom= 2

Sex_Right_Time   No  Unsure  Yes
No change
0               159     462  634
1               421     879  924

Chi2 value= 34.80878775305296
p-value= 2.7629166180201408e-08
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
Positive
0               520    1114  1205
1                60     227   353

Chi2 value= 45.81569401270114
p-value= 1.1252485263724217e-10
Degrees of freedom= 2

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Sex_Right_Time Direction'],dfProfileLast_DiffLast['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Sex_Right_Time             No  Unsure   Yes
Sex_Right_Time Direction
Negative                   56      56    47
No change                 504    1200  1294
Positive                   20      85   217

(115.21091993038107,
 5.626064262276905e-24,
 4,
 array([[  26.50761713,   61.28743892,   71.20494395],
        [ 499.81029031, 1155.59586088, 1342.59384881],
        [  53.68209256,  124.1167002 ,  144.20120724]]))

   Negative  No change  Positive
0         0          0         0
1         0          0         0
2         0          0         0
3         0          1         0
4         0          1         0

Sex_Right_Time   No  Unsure   Yes
Negative
0               524    1285  1511
1                56      56    47

Chi2 value= 43.48484566048368
p-value= 3.6089905229154664e-10
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
No change
0                76     141   264
1               504    1200  1294

Chi2 value= 25.316197467827084
p-value= 3.181687842450502e-06
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
Positive
0               560    1256  1341
1                20      85   217

Chi2 value= 77.3747265958078
p-value= 1.578670888155297e-17
Degrees of freedom= 2

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Weight Direction'],dfProfileLast_DiffLast['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Contraception       No  Yes
Weight Direction
Negative          1608  214
No change          309   19
Positive          1252  112

(17.624317005684993,
 0.000148911482930547,
 2,
 array([[1643.11838361,  178.88161639],
        [ 295.7973819 ,   32.2026181 ],
        [1230.08423449,  133.91576551]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          0         1
4         0          0         1

Contraception    No  Yes
Negative
0              1561  131
1              1608  214

Chi2 value= 15.428680226878239
p-value= 8.567804740517572e-05
Degrees of freedom= 1

Contraception    No  Yes
No change
0              2860  326
1               309   19

Chi2 value= 6.128170003642445
p-value= 0.013304451238155606
Degrees of freedom= 1

Contraception    No  Yes
Positive
0              1917  233
1              1252  112

Chi2 value= 6.206950941562106
p-value= 0.012724962286060095
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Alcohol Direction'],dfProfileLast_DiffLast['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Contraception        No  Yes
Alcohol Direction
Negative            473   69
No change          2421  239
Positive            275   37

(8.7458809504392,
 0.012614094548857218,
 2,
 array([[ 488.78713717,   53.21286283],
        [2398.84462151,  261.15537849],
        [ 281.36824132,   30.63175868]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Contraception    No  Yes
Negative
0              2696  276
1               473   69

Chi2 value= 5.75795372546272
p-value= 0.01641417721642691
Degrees of freedom= 1

Contraception    No  Yes
No change
0               748  106
1              2421  239

Chi2 value= 8.193245857753128
p-value= 0.004204662857230503
Degrees of freedom= 1

Contraception    No  Yes
Positive
0              2894  308
1               275   37

Chi2 value= 1.3680562224789221
p-value= 0.24214613248426864
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Conceive Direction'],dfProfileLast_DiffLast['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Conceive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Contraception         No  Yes
Conceive Direction
Negative             110   31
No change           2896  300
Positive              53    9

(25.24064119704498,
 3.3041853720991994e-06,
 2,
 array([[ 126.89585172,   14.10414828],
        [2876.30597234,  319.69402766],
        [  55.79817593,    6.20182407]]))

   Negative  No change  Positive
0         0          0         0
1         1          0         0
2         0          0         0
3         0          0         0
4         0          1         0

Contraception    No  Yes
Negative
0              3059  314
1               110   31

Chi2 value= 23.153235912687556
p-value= 1.4959125909808606e-06
Degrees of freedom= 1

Contraception    No  Yes
No change
0               273   45
1              2896  300

Chi2 value= 6.886076533204628
p-value= 0.008686973277306389
Degrees of freedom= 1

Contraception    No  Yes
Positive
0              3116  336
1                53    9

Chi2 value= 1.0796605102772678
p-value= 0.2987735145673695
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Month Direction'],dfProfileLast_DiffLast['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Contraception      No  Yes
Month Direction
Negative          382    6
No change        2607  337
Positive          180    2

(54.43359798274195,
 1.513193206928809e-12,
 2,
 array([[ 349.90665908,   38.09334092],
        [2654.96186682,  289.03813318],
        [ 164.1314741 ,   17.8685259 ]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Contraception    No  Yes
Negative
0              2787  339
1               382    6

Chi2 value= 32.66136611513863
p-value= 1.0969605978012744e-08
Degrees of freedom= 1

Contraception    No  Yes
No change
0               562    8
1              2607  337

Chi2 value= 53.277140656706976
p-value= 2.896576879661165e-13
Degrees of freedom= 1

Contraception    No  Yes
Positive
0              2989  343
1               180    2

Chi2 value= 15.457953018289162
p-value= 8.436120213645925e-05
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Menstrual_Information Direction'],dfProfileLast_DiffLast['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Menstrual_Information Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Contraception                      No  Yes
Menstrual_Information Direction
Negative                           76   17
No change                        2706  287
Positive                           43    4

(7.778710859406649,
 0.020458528748834477,
 2,
 array([[  83.85732525,    9.14267475],
        [2698.76316629,  294.23683371],
        [  42.37950846,    4.62049154]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Contraception    No  Yes
Negative
0              3093  328
1                76   17

Chi2 value= 6.774695391603415
p-value= 0.00924592693754248
Degrees of freedom= 1

Contraception    No  Yes
No change
0               463   58
1              2706  287

Chi2 value= 1.0259238433834494
p-value= 0.31111796614549986
Degrees of freedom= 1

Contraception    No  Yes
Positive
0              3126  341
1                43    4

Chi2 value= 0.003187578063995307
p-value= 0.9549764432044687
Degrees of freedom= 1

In [ ]:
contigency = pd.crosstab(dfProfileLast_DiffLast['Contraception Direction'],dfProfileLast_DiffLast['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffLast['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffLast['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

Contraception              No  Yes
Contraception Direction
Negative                  124    7
No change                2993  314
Positive                   52   24

(43.99915742986391,
 2.7906435016979584e-10,
 2,
 array([[ 118.1385885 ,   12.8614115 ],
        [2982.32299374,  324.67700626],
        [  68.53841776,    7.46158224]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          1         0
4         0          1         0

Contraception    No  Yes
Negative
0              3045  338
1               124    7

Chi2 value= 2.5742393600003104
p-value= 0.10861630052668932
Degrees of freedom= 1

Contraception    No  Yes
No change
0               176   31
1              2993  314

Chi2 value= 6.0048129022230405
p-value= 0.014266906807011346
Degrees of freedom= 1

Contraception    No  Yes
Positive
0              3117  321
1                52   24

Chi2 value= 39.07216853420646
p-value= 4.084250003978599e-10
Degrees of freedom= 1

In [ ]:
##dfProfileLast_DiffSecond
##GENDER

contigency = pd.crosstab(dfProfileLast_DiffSecond['Age Direction'],dfProfileLast_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Height Direction'],dfProfileLast_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Weight Direction'],dfProfileLast_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Smoking Direction'],dfProfileLast_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Smoking Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Alcohol Direction'],dfProfileLast_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Conceive Direction'],dfProfileLast_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Conceive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Month Direction'],dfProfileLast_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Children Direction'],dfProfileLast_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Children Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Direction'],dfProfileLast_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['STI Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Positive Direction'],dfProfileLast_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['STI Positive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Frequency Direction'],dfProfileLast_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Right_Time Direction'],dfProfileLast_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Contraception Direction'],dfProfileLast_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##Trying Conceive

contigency = pd.crosstab(dfProfileLast_DiffSecond['Age Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Weight Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")


##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Alcohol Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Conceive Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Conceive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Month Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Children Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Children Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Menstrual_Information Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Menstrual_Information Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Frequency Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")


##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Contraception Direction'],dfProfileLast_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")


##Previous children

contigency = pd.crosstab(dfProfileLast_DiffSecond['Age Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Height Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Weight Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")


##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Alcohol Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Month Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Children Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Children Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Positive Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['STI Positive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Right_Time Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")


##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Contraception Direction'],dfProfileLast_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##STI_Tested
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Height Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Weight Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Smoking Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Smoking Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Alcohol Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Month Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['STI Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Frequency Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Right_Time Direction'],dfProfileLast_DiffSecond['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##STI Positive
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['STI Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['STI_Positive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Positive Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['STI Positive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['STI_Positive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Menstrual_Information Direction'],dfProfileLast_DiffSecond['STI_Positive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Menstrual_Information Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['STI_Positive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##Menstrual_Information
contigency = pd.crosstab(dfProfileLast_DiffSecond['Menstrual_Information Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Menstrual_Information Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Frequency Direction'],dfProfileLast_DiffSecond['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

##Sex_Right_Time
contigency = pd.crosstab(dfProfileLast_DiffSecond['Conceive Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Conceive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileLast_DiffSecond['Month Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileLast_DiffSecond['Children Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Children Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileLast_DiffSecond['STI Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['STI Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Frequency Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileLast_DiffSecond['Sex_Right_Time Direction'],dfProfileLast_DiffSecond['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

##Contraception

contigency = pd.crosstab(dfProfileLast_DiffSecond['Weight Direction'],dfProfileLast_DiffSecond['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Alcohol Direction'],dfProfileLast_DiffSecond['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Conceive Direction'],dfProfileLast_DiffSecond['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Conceive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Month Direction'],dfProfileLast_DiffSecond['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Menstrual_Information Direction'],dfProfileLast_DiffSecond['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Menstrual_Information Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileLast_DiffSecond['Contraception Direction'],dfProfileLast_DiffSecond['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileLast_DiffSecond['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileLast_DiffSecond['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

In [ ]:
##dfProfileFirst_DiffSecond
##GENDER

contigency = pd.crosstab(dfProfileFirst_DiffSecond['Age Direction'],dfProfileFirst_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Height Direction'],dfProfileFirst_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Weight Direction'],dfProfileFirst_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Smoking Direction'],dfProfileFirst_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Smoking Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Alcohol Direction'],dfProfileFirst_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")


##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Month Direction'],dfProfileFirst_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Frequency Direction'],dfProfileFirst_DiffSecond['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
##Trying Conceive

contigency = pd.crosstab(dfProfileFirst_DiffSecond['Age Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Weight Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")


##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Alcohol Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Conceive Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Conceive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Month Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Children Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Children Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Menstrual_Information Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Menstrual_Information Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Frequency Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")


##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Contraception Direction'],dfProfileFirst_DiffSecond['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")


##Previous children

contigency = pd.crosstab(dfProfileFirst_DiffSecond['Age Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Height Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Weight Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Smoking Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Smoking Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")


##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Alcohol Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Month Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Children Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Children Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Positive Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['STI Positive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")


##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Contraception Direction'],dfProfileFirst_DiffSecond['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##STI_Tested
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Height Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Weight Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Smoking Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Smoking Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Alcohol Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['STI Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Frequency Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'],dfProfileFirst_DiffSecond['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##STI Positive
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Month Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['STI_Positive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['STI Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['STI_Positive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Positive Direction'],dfProfileFirst_DiffSecond['STI_Positive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['STI Positive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['STI_Positive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##Menstrual_Information

contigency = pd.crosstab(dfProfileFirst_DiffSecond['Height Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['STI Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['STI Positive Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['STI Positive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Menstrual_Information Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Menstrual_Information Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Frequency Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'],dfProfileFirst_DiffSecond['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

##Sex_Right_Time
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Conceive Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Conceive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileFirst_DiffSecond['Month Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileFirst_DiffSecond['Children Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Children Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Frequency Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Contraception Direction'],dfProfileFirst_DiffSecond['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##Contraception
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Age Direction'],dfProfileFirst_DiffSecond['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Height Direction'],dfProfileFirst_DiffSecond['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Weight Direction'],dfProfileFirst_DiffSecond['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Alcohol Direction'],dfProfileFirst_DiffSecond['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Conceive Direction'],dfProfileFirst_DiffSecond['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Conceive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Month Direction'],dfProfileFirst_DiffSecond['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Menstrual_Information Direction'],dfProfileFirst_DiffSecond['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Menstrual_Information Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffSecond['Contraception Direction'],dfProfileFirst_DiffSecond['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffSecond['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffSecond['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

In [ ]:
##dfProfileFirst_DiffLast
##GENDER

contigency = pd.crosstab(dfProfileFirst_DiffLast['Age Direction'],dfProfileFirst_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Height Direction'],dfProfileFirst_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Weight Direction'],dfProfileFirst_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Smoking Direction'],dfProfileFirst_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Smoking Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Alcohol Direction'],dfProfileFirst_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")


##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Month Direction'],dfProfileFirst_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Frequency Direction'],dfProfileFirst_DiffLast['Gender']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Gender'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
##Trying Conceive

contigency = pd.crosstab(dfProfileFirst_DiffLast['Age Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Weight Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")


##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Alcohol Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Conceive Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Conceive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Month Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Children Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Children Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Menstrual_Information Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Menstrual_Information Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Frequency Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")


##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Contraception Direction'],dfProfileFirst_DiffLast['Trying_Conceive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Trying_Conceive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")


##Previous children

contigency = pd.crosstab(dfProfileFirst_DiffLast['Age Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Height Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Weight Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Smoking Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Smoking Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Month Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Children Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Children Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Positive Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['STI Positive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Contraception Direction'],dfProfileFirst_DiffLast['Previous_Children']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Previous_Children'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##STI_Tested
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Height Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Weight Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Alcohol Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['STI Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Frequency Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Right_Time Direction'],dfProfileFirst_DiffLast['STI_Tested']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['STI_Tested'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##STI Positive


contigency = pd.crosstab(dfProfileFirst_DiffLast['Smoking Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Smoking Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['STI_Positive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Month Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['STI_Positive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['STI Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['STI_Positive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Positive Direction'],dfProfileFirst_DiffLast['STI_Positive']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['STI Positive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['STI_Positive'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##Menstrual_Information
contigency = pd.crosstab(dfProfileFirst_DiffLast['Age Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Age Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['STI Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['STI Positive Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['STI Positive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Menstrual_Information Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Menstrual_Information Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Frequency Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Right_Time Direction'],dfProfileFirst_DiffLast['Menstrual_Information']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Menstrual_Information'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

##Sex_Right_Time
contigency = pd.crosstab(dfProfileFirst_DiffLast['Height Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##contigency = pd.crosstab(dfProfileFirst_DiffLast['Conceive Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Conceive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileFirst_DiffLast['Month Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileFirst_DiffLast['Children Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Children Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Frequency Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Sex_Frequency Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

contigency = pd.crosstab(dfProfileFirst_DiffLast['Sex_Right_Time Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Sex_Right_Time Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Contraception Direction'],dfProfileFirst_DiffLast['Sex_Right_Time']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Sex_Right_Time'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")

##Contraception

contigency = pd.crosstab(dfProfileFirst_DiffLast['Height Direction'],dfProfileFirst_DiffLast['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Height Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Weight Direction'],dfProfileFirst_DiffLast['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Weight Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Smoking Direction'],dfProfileFirst_DiffLast['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Smoking Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Alcohol Direction'],dfProfileFirst_DiffLast['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Alcohol Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Conceive Direction'],dfProfileFirst_DiffLast['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Conceive Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Month Direction'],dfProfileFirst_DiffLast['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Month Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Menstrual_Information Direction'],dfProfileFirst_DiffLast['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Menstrual_Information Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##
contigency = pd.crosstab(dfProfileFirst_DiffLast['Contraception Direction'],dfProfileFirst_DiffLast['Contraception']) 
																			
contigency
stats.chi2_contingency(contigency)
dummies = pd.get_dummies(dfProfileFirst_DiffLast['Contraception Direction'])
dummies.head()
for series in dummies:
    nl = "\n"
    
    crosstab = pd.crosstab(dummies[f"{series}"], dfProfileFirst_DiffLast['Contraception'])
    print(crosstab, nl)
    chi2, p, dof, expected = stats.chi2_contingency(crosstab)
    print(f"Chi2 value= {chi2}{nl}p-value= {p}{nl}Degrees of freedom= {dof}{nl}")
##

Gender         Men  Women
Age Direction
Negative         6    316
No change        6   1500
Positive       344   1958

(264.7605913871355,
 3.220831963968855e-58,
 2,
 array([[  27.7559322 ,  294.2440678 ],
        [ 129.81501211, 1376.18498789],
        [ 198.42905569, 2103.57094431]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          1         0

Gender    Men  Women
Negative
0         350   3458
1           6    316

Chi2 value= 19.319939503248158
p-value= 1.1054589299521429e-05
Degrees of freedom= 1

Gender     Men  Women
No change
0          350   2274
1            6   1500

Chi2 value= 201.76292177633454
p-value= 8.612537668178752e-46
Degrees of freedom= 1

Gender    Men  Women
Positive
0          12   1816
1         344   1958

Chi2 value= 262.22713286291315
p-value= 5.611282941129866e-59
Degrees of freedom= 1

Gender            Men  Women
Height Direction
Negative          158   1091
No change          52    668
Positive          146   2015

(37.07090586906388,
 8.91569228642892e-09,
 2,
 array([[ 107.66198547, 1141.33801453],
        [  62.062954  ,  657.937046  ],
        [ 186.27506053, 1974.72493947]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          0         1

Gender    Men  Women
Negative
0         198   2683
1         158   1091

Chi2 value= 36.19212050037058
p-value= 1.7879200157167112e-09
Degrees of freedom= 1

Gender     Men  Women
No change
0          304   3106
1           52    668

Chi2 value= 1.9529697603519847
p-value= 0.16226718989100541
Degrees of freedom= 1

Gender    Men  Women
Positive
0         210   1759
1         146   2015

Chi2 value= 19.494831090301293
p-value= 1.0087227299043065e-05
Degrees of freedom= 1

Gender            Men  Women
Weight Direction
Negative          232   1924
No change          29    412
Positive           95   1438

(26.308096898640933,
 1.9376232800688753e-06,
 2,
 array([[ 185.8440678 , 1970.1559322 ],
        [  38.01355932,  402.98644068],
        [ 132.14237288, 1400.85762712]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          0         1
4         0          0         1

Gender    Men  Women
Negative
0         124   1850
1         232   1924

Chi2 value= 25.680104436122743
p-value= 4.0296002124117794e-07
Degrees of freedom= 1

Gender     Men  Women
No change
0          327   3362
1           29    412

Chi2 value= 2.3360027489498045
p-value= 0.12641356419272357
Degrees of freedom= 1

Gender    Men  Women
Positive
0         261   2336
1          95   1438

Chi2 value= 17.68281227803333
p-value= 2.6097411837295113e-05
Degrees of freedom= 1

Gender             Men  Women
Smoking Direction
Negative            47    340
No change          294   3327
Positive            15    107

(9.348217728651253,
 0.00933383914976699,
 2,
 array([[  33.35883777,  353.64116223],
        [ 312.12493947, 3308.87506053],
        [  10.51622276,  111.48377724]]))

   Negative  No change  Positive
0         0          1         0
1         1          0         0
2         0          1         0
3         0          1         0
4         0          0         1

Gender    Men  Women
Negative
0         309   3434
1          47    340

Chi2 value= 6.2507916368232115
p-value= 0.012413781506337943
Degrees of freedom= 1

Gender     Men  Women
No change
0           62    447
1          294   3327

Chi2 value= 8.837048167614428
p-value= 0.0029517618106016004
Degrees of freedom= 1

Gender    Men  Women
Positive
0         341   3667
1          15    107

Chi2 value= 1.7017697899427535
p-value= 0.19205668974570994
Degrees of freedom= 1

Gender             Men  Women
Alcohol Direction
Negative            80    553
No change          238   2906
Positive            38    315

(19.437915845290632,
 6.0132630761131436e-05,
 2,
 array([[  54.56368039,  578.43631961],
        [ 271.00823245, 2872.99176755],
        [  30.42808717,  322.57191283]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Gender    Men  Women
Negative
0         276   3221
1          80    553

Chi2 value= 14.72867334043534
p-value= 0.00012414386244765616
Degrees of freedom= 1

Gender     Men  Women
No change
0          118    868
1          238   2906

Chi2 value= 17.874155084864412
p-value= 2.360044953012501e-05
Degrees of freedom= 1

Gender    Men  Women
Positive
0         318   3459
1          38    315

Chi2 value= 1.9667554801789913
p-value= 0.1607926709802532
Degrees of freedom= 1

Gender           Men  Women
Month Direction
Negative          41    351
No change        233   2796
Positive          24    160

(9.339501108978656,
 0.009374607689174282,
 2,
 array([[  32.4038835 ,  359.5961165 ],
        [ 250.38613037, 2778.61386963],
        [  15.20998613,  168.79001387]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Gender    Men  Women
Negative
0         315   3423
1          41    351

Chi2 value= 1.6111644745744984
p-value= 0.20432819010098943
Degrees of freedom= 1

Gender     Men  Women
No change
0          123    978
1          233   2796

Chi2 value= 11.972505379663438
p-value= 0.0005399129912773198
Degrees of freedom= 1

Gender    Men  Women
Positive
0         332   3614
1          24    160

Chi2 value= 4.214533509217626
p-value= 0.0400790852600416
Degrees of freedom= 1

Gender                   Men  Women
Sex_Frequency Direction
Negative                  66    559
No change                176   2159
Positive                  56    589

(6.119017719499393,
 0.04691072931037643,
 2,
 array([[  51.66435506,  573.33564494],
        [ 193.01803051, 2141.98196949],
        [  53.31761442,  591.68238558]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Gender    Men  Women
Negative
0         290   3215
1          66    559

Chi2 value= 3.235072251816843
p-value= 0.07207712403472787
Degrees of freedom= 1

Gender     Men  Women
No change
0          180   1615
1          176   2159

Chi2 value= 7.67759921183109
p-value= 0.005591050199937886
Degrees of freedom= 1

Gender    Men  Women
Positive
0         300   3185
1          56    589

Chi2 value= 0.00022430848763566112
p-value= 0.9880505840363656
Degrees of freedom= 1

Trying_Conceive   No   Yes
Age Direction
Negative          91   194
No change        377   886
Positive         466  1444

(15.275065006920343,
 0.00048201635957621227,
 2,
 array([[  76.97802198,  208.02197802],
        [ 341.13418161,  921.86581839],
        [ 515.88779641, 1394.11220359]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          1         0

Trying_Conceive   No   Yes
Negative
0                843  2330
1                 91   194

Chi2 value= 3.546535074903933
p-value= 0.05966993009417283
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                557  1638
1                377   886

Chi2 value= 7.913494224987534
p-value= 0.00490674035482635
Degrees of freedom= 1

Trying_Conceive   No   Yes
Positive
0                468  1080
1                466  1444

Chi2 value= 14.470172715727992
p-value= 0.0001423965701927894
Degrees of freedom= 1

Trying_Conceive    No   Yes
Weight Direction
Negative          533  1260
No change          82   246
Positive          319  1018

(14.116502964314877,
 0.0008602809963373467,
 2,
 array([[ 484.28629265, 1308.71370735],
        [  88.59224986,  239.40775014],
        [ 361.12145749,  975.87854251]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          0         1
4         0          0         1

Trying_Conceive   No   Yes
Negative
0                401  1264
1                533  1260

Chi2 value= 13.657942104528457
p-value= 0.00021931172419746326
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                852  2278
1                 82   246

Chi2 value= 0.6341266003960216
p-value= 0.42584567773140436
Degrees of freedom= 1

Trying_Conceive   No   Yes
Positive
0                615  1506
1                319  1018

Chi2 value= 10.715223462679585
p-value= 0.0010625762433136789
Degrees of freedom= 1

Trying_Conceive     No   Yes
Alcohol Direction
Negative           164   373
No change          676  1945
Positive            94   206

(8.21189134405542,
 0.01647443205996196,
 2,
 array([[ 145.04279931,  391.95720069],
        [ 707.92770388, 1913.07229612],
        [  81.02949682,  218.97050318]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Trying_Conceive   No   Yes
Negative
0                770  2151
1                164   373

Chi2 value= 3.809470075524093
p-value= 0.050963571914728174
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                258   579
1                676  1945

Chi2 value= 7.897171433044973
p-value= 0.004951216259081894
Degrees of freedom= 1

Trying_Conceive   No   Yes
Positive
0                840  2318
1                 94   206

Chi2 value= 2.879209818065923
p-value= 0.0897300440424986
Degrees of freedom= 1

Trying_Conceive      No   Yes
Conceive Direction
Negative              0   148
No change           870  2376
Positive             64     0

(227.78875614282822,
 3.437954176329376e-50,
 2,
 array([[  39.97455176,  108.02544824],
        [ 876.73915558, 2369.26084442],
        [  17.28629265,   46.71370735]]))

   Negative  No change  Positive
0         0          0         0
1         1          0         0
2         0          0         0
3         0          0         0
4         0          1         0

Trying_Conceive   No   Yes
Negative
0                934  2376
1                  0   148

Chi2 value= 55.79347934784011
p-value= 8.049809860622427e-14
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                 64   148
1                870  2376

Chi2 value= 0.9922154711233281
p-value= 0.31920149620058585
Degrees of freedom= 1

Trying_Conceive   No   Yes
Positive
0                870  2524
1                 64     0

Chi2 value= 172.46006586196566
p-value= 2.1472646810791602e-39
Degrees of freedom= 1

Trying_Conceive   No   Yes
Month Direction
Negative           3   389
No change        928  1954
Positive           3   181

(236.44880200218745,
 4.526838688402659e-52,
 2,
 array([[ 105.87854251,  286.12145749],
        [ 778.42336611, 2103.57663389],
        [  49.69809138,  134.30190862]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Trying_Conceive   No   Yes
Negative
0                931  2135
1                  3   389

Chi2 value= 152.96723181543692
p-value= 3.8943443407225754e-35
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                  6   570
1                928  1954

Chi2 value= 234.82343466416225
p-value= 5.290274808339984e-53
Degrees of freedom= 1

Trying_Conceive   No   Yes
Positive
0                931  2343
1                  3   181

Chi2 value= 62.14272723907973
p-value= 3.194446057880313e-15
Degrees of freedom= 1

Trying_Conceive      No   Yes
Children Direction
Negative              6    51
No change           893  2393
Positive             24    36

(12.980995939027165,
 0.0015177930052057951,
 2,
 array([[  15.46018219,   41.53981781],
        [ 891.26594182, 2394.73405818],
        [  16.27387599,   43.72612401]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Trying_Conceive   No   Yes
Negative
0                928  2473
1                  6    51

Chi2 value= 7.159920067832502
p-value= 0.007455051885062674
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                 41   131
1                893  2393

Chi2 value= 0.762544276959188
p-value= 0.3825334687040073
Degrees of freedom= 1

Trying_Conceive   No   Yes
Positive
0                910  2488
1                 24    36

Chi2 value= 4.577281446279124
p-value= 0.03239857668837015
Degrees of freedom= 1

Trying_Conceive                   No   Yes
Menstrual_Information Direction
Negative                          35    61
No change                        787  2160
Positive                          18    29

(7.445718824020318,
 0.024164771923951035,
 2,
 array([[  26.09708738,   69.90291262],
        [ 801.12621359, 2145.87378641],
        [  12.77669903,   34.22330097]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Trying_Conceive   No   Yes
Negative
0                899  2463
1                 35    61

Chi2 value= 3.99197948074496
p-value= 0.04571732535328872
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                147   364
1                787  2160

Chi2 value= 0.8375380122234507
p-value= 0.3601018511606917
Degrees of freedom= 1

Trying_Conceive   No   Yes
Positive
0                916  2495
1                 18    29

Chi2 value= 2.5264716222010826
p-value= 0.11195029518883959
Degrees of freedom= 1

Trying_Conceive           No   Yes
Sex_Frequency Direction
Negative                 168   442
No change                630  1590
Positive                 136   492

(11.326838795070532,
 0.0034706291246082033,
 2,
 array([[ 164.75997687,  445.24002313],
        [ 599.61827646, 1620.38172354],
        [ 169.62174667,  458.37825333]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Trying_Conceive   No   Yes
Negative
0                766  2082
1                168   442

Chi2 value= 0.07580142663682181
p-value= 0.7830699478731195
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                304   934
1                630  1590

Chi2 value= 5.698708043011453
p-value= 0.016977405366023303
Degrees of freedom= 1

Trying_Conceive   No   Yes
Positive
0                798  2032
1                136   492

Chi2 value= 10.827273895863296
p-value= 0.0010001578681639943
Degrees of freedom= 1

Trying_Conceive           No   Yes
Contraception Direction
Negative                  65    64
No change                812  2383
Positive                  32    43

(49.396674821529864,
 1.8777957436467533e-11,
 2,
 array([[  34.49867608,   94.50132392],
        [ 854.4439541 , 2340.5560459 ],
        [  20.05736981,   54.94263019]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          1         0
4         0          1         0

Trying_Conceive   No   Yes
Negative
0                869  2460
1                 65    64

Chi2 value= 35.92517849321357
p-value= 2.050418586590843e-09
Degrees of freedom= 1

Trying_Conceive   No   Yes
No change
0                122   141
1                812  2383

Chi2 value= 53.159134484491204
p-value= 3.0759174889293674e-13
Degrees of freedom= 1

Trying_Conceive   No   Yes
Positive
0                902  2481
1                 32    43

Chi2 value= 8.737978869043136
p-value= 0.0031164976395479855
Degrees of freedom= 1

Previous_Children    No  Yes
Age Direction
Negative            216   68
No change           869  407
Positive           1260  681

(15.049079221834534,
 0.0005396770726398847,
 2,
 array([[ 190.22564981,   93.77435019],
        [ 854.67580691,  421.32419309],
        [1300.09854327,  640.90145673]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          1         0

Previous_Children    No   Yes
Negative
0                  2129  1088
1                   216    68

Chi2 value= 11.067926011178677
p-value= 0.0008783387251277212
Degrees of freedom= 1

Previous_Children    No  Yes
No change
0                  1476  749
1                   869  407

Chi2 value= 1.0655517427442036
p-value= 0.3019523677764834
Degrees of freedom= 1

Previous_Children    No  Yes
Positive
0                  1085  475
1                  1260  681

Chi2 value= 8.197547403956847
p-value= 0.004194705547636857
Degrees of freedom= 1

Previous_Children    No  Yes
Height Direction
Negative            711  339
No change           335  216
Positive           1299  601

(11.43159382921956,
 0.0032935248175175865,
 2,
 array([[ 703.29905741,  346.70094259],
        [ 369.06455298,  181.93544702],
        [1272.6363896 ,  627.3636104 ]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          0         1

Previous_Children    No  Yes
Negative
0                  1634  817
1                   711  339

Chi2 value= 0.3189493618537454
p-value= 0.5722397250945173
Degrees of freedom= 1

Previous_Children    No  Yes
No change
0                  2010  940
1                   335  216

Chi2 value= 10.97144351431259
p-value= 0.0009252665761429962
Degrees of freedom= 1

Previous_Children    No  Yes
Positive
0                  1046  555
1                  1299  601

Chi2 value= 3.4810400294438066
p-value= 0.06207571423675247
Degrees of freedom= 1

Previous_Children    No  Yes
Weight Direction
Negative           1332  480
No change           189  145
Positive            824  531

(74.55740318632274,
 6.457517704871958e-17,
 2,
 array([[1213.69323051,  598.30676949],
        [ 223.71608112,  110.28391888],
        [ 907.59068837,  447.40931163]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          0         1
4         0          0         1

Previous_Children    No  Yes
Negative
0                  1013  676
1                  1332  480

Chi2 value= 71.78410699207099
p-value= 2.4007814536438412e-17
Degrees of freedom= 1

Previous_Children    No   Yes
No change
0                  2156  1011
1                   189   145

Chi2 value= 17.520304696367354
p-value= 2.842556991134937e-05
Degrees of freedom= 1

Previous_Children    No  Yes
Positive
0                  1521  625
1                   824  531

Chi2 value= 37.584722859723335
p-value= 8.75273316873749e-10
Degrees of freedom= 1

Previous_Children    No  Yes
Smoking Direction
Negative            220  117
No change          2067  986
Positive             58   53

(12.049028545373263,
 0.0024187261234261377,
 2,
 array([[ 225.725507 ,  111.274493 ],
        [2044.9257355, 1008.0742645],
        [  74.3487575,   36.6512425]]))

   Negative  No change  Positive
0         0          1         0
1         1          0         0
2         0          1         0
3         0          1         0
4         0          0         1

Previous_Children    No   Yes
Negative
0                  2125  1039
1                   220   117

Chi2 value= 0.4053835698694083
p-value= 0.5243219722247551
Degrees of freedom= 1

Previous_Children    No  Yes
No change
0                   278  170
1                  2067  986

Chi2 value= 5.386948584191498
p-value= 0.020287918364241323
Degrees of freedom= 1

Previous_Children    No   Yes
Positive
0                  2287  1103
1                    58    53

Chi2 value= 10.566798230365277
p-value= 0.0011513697569881306
Degrees of freedom= 1

Previous_Children    No  Yes
Month Direction
Negative            236  152
No change          1986  944
Positive            123   60

(7.5024256684934585,
 0.023489240018351395,
 2,
 array([[ 259.88574693,  128.11425307],
        [1962.53927449,  967.46072551],
        [ 122.57497858,   60.42502142]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Previous_Children    No   Yes
Negative
0                  2109  1004
1                   236   152

Chi2 value= 7.167493307850133
p-value= 0.007423643609407609
Degrees of freedom= 1

Previous_Children    No  Yes
No change
0                   359  212
1                  1986  944

Chi2 value= 4.988191705713854
p-value= 0.025520865082137915
Degrees of freedom= 1

Previous_Children    No   Yes
Positive
0                  2222  1096
1                   123    60

Chi2 value= 0.00014656240189654847
p-value= 0.990340809310442
Degrees of freedom= 1

Previous_Children     No   Yes
Children Direction
Negative               0    59
No change           2285  1097
Positive              60     0

(149.78131262180122,
 2.9881419053789696e-33,
 2,
 array([[  39.51870894,   19.48129106],
        [2265.29277349, 1116.70722651],
        [  40.18851757,   19.81148243]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Previous_Children    No   Yes
Negative
0                  2345  1097
1                     0    59

Chi2 value= 118.67481518492829
p-value= 1.2338620997229216e-27
Degrees of freedom= 1

Previous_Children    No   Yes
No change
0                    60    59
1                  2285  1097

Chi2 value= 14.51056765451653
p-value= 0.00013937549259795235
Degrees of freedom= 1

Previous_Children    No   Yes
Positive
0                  2285  1156
1                    60     0

Chi2 value= 28.59373941316344
p-value= 8.927034405343282e-08
Degrees of freedom= 1

Previous_Children         No  Yes
STI Positive Direction
Negative                  67   28
No change               1571  840
Positive                  40    6

(10.52211555622831,
 0.005189812144551915,
 2,
 array([[  62.46473354,   32.53526646],
        [1585.28918495,  825.71081505],
        [  30.2460815 ,   15.7539185 ]]))

   Negative  No change  Positive
0         0          0         0
1         0          0         0
2         0          0         0
3         0          0         0
4         0          0         0

Previous_Children    No   Yes
Negative
0                  2278  1128
1                    67    28

Chi2 value= 0.4024578158217685
p-value= 0.5258226605625759
Degrees of freedom= 1

Previous_Children    No  Yes
No change
0                   774  316
1                  1571  840

Chi2 value= 11.350198383364635
p-value= 0.0007543991029900707
Degrees of freedom= 1

Previous_Children    No   Yes
Positive
0                  2305  1150
1                    40     6

Chi2 value= 7.51951255763696
p-value= 0.006103419358931617
Degrees of freedom= 1

Previous_Children          No   Yes
Contraception Direction
Negative                  101    28
No change                2142  1098
Positive                   60    16

(13.44160844841168,
 0.0012055682767968534,
 2,
 array([[  86.2371553 ,   42.7628447 ],
        [2165.95645864, 1074.04354136],
        [  50.80638607,   25.19361393]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          1         0
4         0          1         0

Previous_Children    No   Yes
Negative
0                  2244  1128
1                   101    28

Chi2 value= 7.229516631193273
p-value= 0.007171451382405811
Degrees of freedom= 1

Previous_Children    No   Yes
No change
0                   203    58
1                  2142  1098

Chi2 value= 14.3423623953873
p-value= 0.00015239666744376433
Degrees of freedom= 1

Previous_Children    No   Yes
Positive
0                  2285  1140
1                    60    16

Chi2 value= 4.4920771207677355
p-value= 0.03405227942006331
Degrees of freedom= 1

STI_Tested         No   Yes
Height Direction
Negative          498   568
No change         248   306
Positive          746  1167

(18.455045419055985,
 9.829644369646634e-05,
 2,
 array([[ 450.17605434,  615.82394566],
        [ 233.95641098,  320.04358902],
        [ 807.86753467, 1105.13246533]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          0         1

STI_Tested   No   Yes
Negative
0           994  1473
1           498   568

Chi2 value= 12.332599390417935
p-value= 0.00044511615364148583
Degrees of freedom= 1

STI_Tested    No   Yes
No change
0           1244  1735
1            248   306

Chi2 value= 1.6095569573173547
p-value= 0.20455409142651745
Degrees of freedom= 1

STI_Tested   No   Yes
Positive
0           746   874
1           746  1167

Chi2 value= 17.59812722939079
p-value= 2.7285691958819762e-05
Degrees of freedom= 1

STI_Tested         No  Yes
Weight Direction
Negative          850  988
No change         144  189
Positive          498  864

(30.21411892487226,
 2.7484474497420017e-07,
 2,
 array([[ 776.19473535, 1061.80526465],
        [ 140.62722898,  192.37277102],
        [ 575.17803566,  786.82196434]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          0         1
4         0          0         1

STI_Tested   No   Yes
Negative
0           642  1053
1           850   988

Chi2 value= 24.978951618780773
p-value= 5.795961279827562e-07
Degrees of freedom= 1

STI_Tested    No   Yes
No change
0           1348  1852
1            144   189

Chi2 value= 0.11215713155127816
p-value= 0.737701511469061
Degrees of freedom= 1

STI_Tested   No   Yes
Positive
0           994  1177
1           498   864

Chi2 value= 28.795465964803967
p-value= 8.043920350652498e-08
Degrees of freedom= 1

STI_Tested           No   Yes
Alcohol Direction
Negative            215   334
No change          1178  1499
Positive             99   208

(18.112866093485096,
 0.00011663827875171545,
 2,
 array([[ 231.84489103,  317.15510897],
        [1130.50778375, 1546.49221625],
        [ 129.64732522,  177.35267478]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

STI_Tested    No   Yes
Negative
0           1277  1707
1            215   334

Chi2 value= 2.361630669122312
p-value= 0.12435214215951232
Degrees of freedom= 1

STI_Tested    No   Yes
No change
0            314   542
1           1178  1499

Chi2 value= 13.955609348659761
p-value= 0.00018717831192324274
Degrees of freedom= 1

STI_Tested    No   Yes
Positive
0           1393  1833
1             99   208

Chi2 value= 13.289661460570063
p-value= 0.00026687366619770306
Degrees of freedom= 1

STI_Tested      No   Yes
STI Direction
Negative         0   115
No change      976  1926
Positive       516     0

(877.8800900696219,
 2.3483377255878802e-191,
 2,
 array([[  48.56495896,   66.43504104],
        [1225.52618172, 1676.47381828],
        [ 217.90885933,  298.09114067]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

STI_Tested    No   Yes
Negative
0           1492  1926
1              0   115

Chi2 value= 85.11504583265166
p-value= 2.8150034304636486e-20
Degrees of freedom= 1

STI_Tested   No   Yes
No change
0           516   115
1           976  1926

Chi2 value= 490.43599406821335
p-value= 1.145367510838906e-108
Degrees of freedom= 1

STI_Tested   No   Yes
Positive
0           976  2041
1           516     0

Chi2 value= 823.8232960830364
p-value= 3.568959928320936e-181
Degrees of freedom= 1

STI_Tested                 No   Yes
Sex_Frequency Direction
Negative                  253   368
No change                1004  1273
Positive                  235   400

(10.90244729850798,
 0.004291050735877142,
 2,
 array([[ 262.25077838,  358.74922162],
        [ 961.58618738, 1315.41381262],
        [ 268.16303425,  366.83696575]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

STI_Tested    No   Yes
Negative
0           1239  1673
1            253   368

Chi2 value= 0.6132385999614007
p-value= 0.43357101933176667
Degrees of freedom= 1

STI_Tested    No   Yes
No change
0            488   768
1           1004  1273

Chi2 value= 8.895712725193517
p-value= 0.002858410094022424
Degrees of freedom= 1

STI_Tested    No   Yes
Positive
0           1257  1641
1            235   400

Chi2 value= 8.395760293116687
p-value= 0.0037609717258964555
Degrees of freedom= 1

STI_Tested                  No   Yes
Sex_Right_Time Direction
Negative                    80    79
No change                 1254  1711
Positive                   114   205

(9.746073049495143,
 0.007650100264587374,
 2,
 array([[  66.86959047,   92.13040953],
        [1246.97066512, 1718.02933488],
        [ 134.15974441,  184.84025559]]))

   Negative  No change  Positive
0         0          0         0
1         0          0         0
2         0          0         0
3         0          1         0
4         0          1         0

STI_Tested    No   Yes
Negative
0           1412  1962
1             80    79

Chi2 value= 4.11972809489588
p-value= 0.042385890260528206
Degrees of freedom= 1

STI_Tested    No   Yes
No change
0            238   330
1           1254  1711

Chi2 value= 0.01610799742174698
p-value= 0.8990058652299412
Degrees of freedom= 1

STI_Tested    No   Yes
Positive
0           1378  1836
1            114   205

Chi2 value= 5.772033791460986
p-value= 0.01628317937609792
Degrees of freedom= 1

STI_Positive         No  Yes
Smoking Direction
Negative            226   28
No change          2064  175
Positive             78   12

(6.142691581189741,
 0.04635872372286067,
 2,
 array([[ 232.85791715,   21.14208285],
        [2052.63337205,  186.36662795],
        [  82.5087108 ,    7.4912892 ]]))

   Negative  No change  Positive
0         0          1         0
1         1          0         0
2         0          1         0
3         0          1         0
4         0          0         1

STI_Positive    No  Yes
Negative
0             2142  187
1              226   28

Chi2 value= 2.313021044568547
p-value= 0.12829448642552305
Degrees of freedom= 1

STI_Positive    No  Yes
No change
0              304   40
1             2064  175

Chi2 value= 5.189555018110118
p-value= 0.02272303370339544
Degrees of freedom= 1

STI_Positive    No  Yes
Positive
0             2290  203
1               78   12

Chi2 value= 2.4243634345991216
p-value= 0.11946176087746595
Degrees of freedom= 1

STI_Positive       No  Yes
Month Direction
Negative          286   27
No change        1977  168
Positive          105   20

(10.369235050680459,
 0.005602078858810996,
 2,
 array([[ 286.9469609 ,   26.0530391 ],
        [1966.45760743,  178.54239257],
        [ 114.59543167,   10.40456833]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

STI_Positive    No  Yes
Negative
0             2082  188
1              286   27

Chi2 value= 0.009517479016271202
p-value= 0.9222836197821147
Degrees of freedom= 1

STI_Positive    No  Yes
No change
0              391   47
1             1977  168

Chi2 value= 3.633507343381184
p-value= 0.05662736131408876
Degrees of freedom= 1

STI_Positive    No  Yes
Positive
0             2263  195
1              105   20

Chi2 value= 9.113974307215717
p-value= 0.0025366414833097113
Degrees of freedom= 1

STI_Positive     No  Yes
STI Direction
Negative         75   16
No change      1814  175
Positive        479   24

(19.128253116860577,
 7.02025053775622e-05,
 2,
 array([[  83.42547425,    7.57452575],
        [1823.44250871,  165.55749129],
        [ 461.13201703,   41.86798297]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

STI_Positive    No  Yes
Negative
0             2293  199
1               75   16

Chi2 value= 9.37592553218661
p-value= 0.002198536738031267
Degrees of freedom= 1

STI_Positive    No  Yes
No change
0              554   40
1             1814  175

Chi2 value= 2.2911344534554376
p-value= 0.13011478924411837
Degrees of freedom= 1

STI_Positive    No  Yes
Positive
0             1889  191
1              479   24

Chi2 value= 9.759341373463766
p-value= 0.0017841381716554568
Degrees of freedom= 1

STI_Positive              No  Yes
STI Positive Direction
Negative                   0   95
No change               2322  120
Positive                  46    0

(1087.7064629125439,
 6.42011213022779e-237,
 2,
 array([[  87.09252807,    7.90747193],
        [2238.73635308,  203.26364692],
        [  42.17111885,    3.82888115]]))

   Negative  No change  Positive
0         0          0         0
1         0          0         0
2         0          0         0
3         0          0         0
4         0          0         0

STI_Positive    No  Yes
Negative
0             2368  120
1                0   95

Chi2 value= 1073.8408411092898
p-value= 1.6013665076142288e-235
Degrees of freedom= 1

STI_Positive    No  Yes
No change
0               46   95
1             2322  120

Chi2 value= 673.3913399141585
p-value= 1.8284883419802948e-148
Degrees of freedom= 1

STI_Positive    No  Yes
Positive
0             2322  215
1               46    0

Chi2 value= 3.214188482229294
p-value= 0.0730023827141599
Degrees of freedom= 1

Menstrual_Information    No  Yes
Age Direction
Negative                178   46
No change              1110  166
Positive               1451  225

(9.431045045677642,
 0.008955185555169791,
 2,
 array([[ 193.17884131,   30.82115869],
        [1100.42947103,  175.57052897],
        [1445.39168766,  230.60831234]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          1         0

Menstrual_Information    No  Yes
Negative
0                      2561  391
1                       178   46

Chi2 value= 8.721419798644364
p-value= 0.003144930321305454
Degrees of freedom= 1

Menstrual_Information    No  Yes
No change
0                      1629  271
1                      1110  166

Chi2 value= 0.9082992716167936
p-value= 0.34056607504174213
Degrees of freedom= 1

Menstrual_Information    No  Yes
Positive
0                      1288  212
1                      1451  225

Chi2 value= 0.2778162382511916
p-value= 0.5981361166831958
Degrees of freedom= 1

Menstrual_Information    No  Yes
STI Direction
Negative                 80   26
No change              2246  342
Positive                401   69

(11.299241515961144,
 0.0035188510180617595,
 2,
 array([[  91.3596713 ,   14.6403287 ],
        [2230.55499368,  357.44500632],
        [ 405.08533502,   64.91466498]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Menstrual_Information    No  Yes
Negative
0                      2659  411
1                        80   26

Chi2 value= 9.79874033644581
p-value= 0.0017463145017673392
Degrees of freedom= 1

Menstrual_Information    No  Yes
No change
0                       493   95
1                      2246  342

Chi2 value= 3.2505004954526635
p-value= 0.07140165208521329
Degrees of freedom= 1

Menstrual_Information    No  Yes
Positive
0                      2338  368
1                       401   69

Chi2 value= 0.3087997916114346
p-value= 0.5784176166308777
Degrees of freedom= 1

Menstrual_Information     No  Yes
STI Positive Direction
Negative                  75   12
No change               1928  300
Positive                  33   12

(6.490956436358605,
 0.03894993333658974,
 2,
 array([[  75.0559322,   11.9440678],
        [1922.1220339,  305.8779661],
        [  38.8220339,    6.1779661]]))

   Negative  No change  Positive
0         0          0         0
1         0          0         0
2         0          0         0
3         0          0         0
4         0          0         0

Menstrual_Information    No  Yes
Negative
0                      2664  425
1                        75   12

Chi2 value= 0.022067454963691117
p-value= 0.8819077931586212
Degrees of freedom= 1

Menstrual_Information    No  Yes
No change
0                       811  137
1                      1928  300

Chi2 value= 0.4654303726455341
p-value= 0.49509695668866205
Degrees of freedom= 1

Menstrual_Information    No  Yes
Positive
0                      2706  425
1                        33   12

Chi2 value= 5.352726635329818
p-value= 0.02068989112903356
Degrees of freedom= 1

Menstrual_Information              No  Yes
Menstrual_Information Direction
Negative                            0   97
No change                        2692  340
Positive                           47    0

(632.0281936527059,
 5.712438594411314e-138,
 2,
 array([[  83.65333753,   13.34666247],
        [2614.81360202,  417.18639798],
        [  40.53306045,    6.46693955]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Menstrual_Information    No  Yes
Negative
0                      2739  340
1                         0   97

Chi2 value= 619.6492941176274
p-value= 8.913216192550172e-137
Degrees of freedom= 1

Menstrual_Information    No  Yes
No change
0                        47   97
1                      2692  340

Chi2 value= 360.50641840073905
p-value= 2.184303707126836e-80
Degrees of freedom= 1

Menstrual_Information    No  Yes
Positive
0                      2692  437
1                        47    0

Chi2 value= 6.4798934787401095
p-value= 0.010910152184096102
Degrees of freedom= 1

Menstrual_Information      No  Yes
Sex_Frequency Direction
Negative                  463   97
No change                1776  272
Positive                  500   68

(7.911974172716063,
 0.01913976661973341,
 2,
 array([[ 482.94710327,   77.05289673],
        [1766.20654912,  281.79345088],
        [ 489.84634761,   78.15365239]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Menstrual_Information    No  Yes
Negative
0                      2276  340
1                       463   97

Chi2 value= 6.909586951921225
p-value= 0.008573479413033838
Degrees of freedom= 1

Menstrual_Information    No  Yes
No change
0                       963  165
1                      1776  272

Chi2 value= 1.0006517884693213
p-value= 0.3171528455160071
Degrees of freedom= 1

Menstrual_Information    No  Yes
Positive
0                      2239  369
1                       500   68

Chi2 value= 1.6838189886073414
p-value= 0.19441777068912994
Degrees of freedom= 1

Menstrual_Information       No  Yes
Sex_Right_Time Direction
Negative                   114   28
No change                 2299  367
Positive                   267   28

(8.803801967079236,
 0.012254023051499677,
 2,
 array([[ 122.64260393,   19.35739607],
        [2302.5717048 ,  363.4282952 ],
        [ 254.78569127,   40.21430873]]))

   Negative  No change  Positive
0         0          0         0
1         0          0         0
2         0          0         0
3         0          1         0
4         0          1         0

Menstrual_Information    No  Yes
Negative
0                      2625  409
1                       114   28

Chi2 value= 3.9378880994818033
p-value= 0.047210010370414744
Degrees of freedom= 1

Menstrual_Information    No  Yes
No change
0                       440   70
1                      2299  367

Chi2 value= 0.0021026714135523655
p-value= 0.9634259047512189
Degrees of freedom= 1

Menstrual_Information    No  Yes
Positive
0                      2472  409
1                       267   28

Chi2 value= 4.6034303770929155
p-value= 0.031908050066755296
Degrees of freedom= 1

Sex_Right_Time     No  Unsure  Yes
Height Direction
Negative          209     440  407
No change         124     213  210
Positive          320     781  775

(10.488033538672864,
 0.032962224641916796,
 4,
 array([[198.20868066, 435.26990515, 422.5214142 ],
        [102.670595  , 225.46651337, 218.86289164],
        [352.12072435, 773.26358149, 750.61569416]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          0         1

Sex_Right_Time   No  Unsure  Yes
Negative
0               444     994  985
1               209     440  407

Chi2 value= 1.736067912923711
p-value= 0.41977603645713213
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
No change
0               529    1221  1182
1               124     213   210

Chi2 value= 6.501532364369807
p-value= 0.0387445111024528
Degrees of freedom= 2

Sex_Right_Time   No  Unsure  Yes
Positive
0               333     653  617
1               320     781  775

Chi2 value= 8.246340134557995
p-value= 0.016193099775287358
Degrees of freedom= 2

Sex_Right_Time     No  Unsure  Yes
Height Direction
Negative          209     440  407
No change         124     213  210
Positive          320     781  775

(10.488033538672864,
 0.032962224641916796,
 4,
 array([[198.20868066, 435.26990515, 422.5214142 ],
        [102.670595  , 225.46651337, 218.86289164],
        [352.12072435, 773.26358149, 750.61569416]]))

   Negative  No change  Positive
0         0          0         0
1         1          0         0
2         0          0         0
3         0          0         0
4         0          1         0

Sex_Right_Time   No  Unsure   Yes
Negative
0               611    1373  1355
1                42      61    37

Chi2 value= 16.723391134768825
p-value= 0.00023364783207297781
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
No change
0                91     127    98
1               562    1307  1294

Chi2 value= 25.74402464199215
p-value= 2.568952522339845e-06
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
Positive
0               634    1406  1376
1                19      28    16

Chi2 value= 8.020959727581968
p-value= 0.01812469576446715
Degrees of freedom= 2

Sex_Right_Time    No  Unsure   Yes
Month Direction
Negative          51     142   196
No change        581    1219  1108
Positive          21      73    88

(32.750659884517994,
 1.3434379953925403e-06,
 4,
 array([[  73.01437195,  160.34090256,  155.6447255 ],
        [ 545.82466226, 1198.64098879, 1163.53434895],
        [  34.16096579,   75.01810865,   72.82092555]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Sex_Right_Time   No  Unsure   Yes
Negative
0               602    1292  1196
1                51     142   196

Chi2 value= 21.61561856094091
p-value= 2.0240818381973736e-05
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
No change
0                72     215   284
1               581    1219  1108

Chi2 value= 32.06804751003279
p-value= 1.0877070927236692e-07
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
Positive
0               632    1361  1304
1                21      73    88

Chi2 value= 8.746263044192279
p-value= 0.012611684895678968
Degrees of freedom= 2

Sex_Right_Time       No  Unsure   Yes
Children Direction
Negative              8      15    34
No change           615    1366  1316
Positive             13      26    21

(9.95531053497104,
 0.04118723617713877,
 4,
 array([[  10.61862917,   23.49121265,   22.89015817],
        [ 614.20386643, 1358.78119508, 1324.01493849],
        [  11.17750439,   24.72759227,   24.09490334]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Sex_Right_Time   No  Unsure   Yes
Negative
0               645    1419  1358
1                 8      15    34

Chi2 value= 9.399826355579822
p-value= 0.009096066808036679
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
No change
0                38      68    76
1               615    1366  1316

Chi2 value= 1.2944990467152206
p-value= 0.5234836279578614
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
Positive
0               640    1408  1371
1                13      26    21

Chi2 value= 0.7224301532794146
p-value= 0.6968291106851939
Degrees of freedom= 2

Sex_Right_Time            No  Unsure  Yes
Sex_Frequency Direction
Negative                 111     267  237
No change                462     902  860
Positive                  80     265  295

(26.5448431293087,
 2.4567344619383957e-05,
 4,
 array([[115.43403277, 253.49525726, 246.07070997],
        [417.43949411, 916.70480023, 889.85570566],
        [120.12647312, 263.79994251, 256.07358436]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Sex_Right_Time   No  Unsure   Yes
Negative
0               542    1167  1155
1               111     267   237

Chi2 value= 1.487004454100034
p-value= 0.47544587689012063
Degrees of freedom= 2

Sex_Right_Time   No  Unsure  Yes
No change
0               191     532  532
1               462     902  860

Chi2 value= 16.616820952773143
p-value= 0.0002464354471693537
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
Positive
0               573    1169  1097
1                80     265   295

Chi2 value= 23.68320471806698
p-value= 7.198755752466119e-06
Degrees of freedom= 2

Sex_Right_Time             No  Unsure   Yes
Sex_Right_Time Direction
Negative                    0      61    98
No change                 504    1200  1294
Positive                  149     173     0

(334.1661628112126,
 4.594769476939525e-71,
 4,
 array([[  29.84392067,   65.53779822,   63.61828112],
        [ 562.71744754, 1235.73785571, 1199.54469675],
        [  60.43863179,  132.72434608,  128.83702213]]))

   Negative  No change  Positive
0         0          0         0
1         0          0         0
2         0          0         0
3         0          1         0
4         0          1         0

Sex_Right_Time   No  Unsure   Yes
Negative
0               653    1373  1294
1                 0      61    98

Chi2 value= 51.07349400863349
p-value= 8.119544947149612e-12
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
No change
0               149     234    98
1               504    1200  1294

Chi2 value= 105.5862143161461
p-value= 1.1809863519406733e-23
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
Positive
0               504    1261  1392
1               149     173     0

Chi2 value= 298.4520466346148
p-value= 1.5558277627441888e-65
Degrees of freedom= 2

Sex_Right_Time            No  Unsure   Yes
Contraception Direction
Negative                  23      63    43
No change                606    1317  1324
Positive                  13      42    19

(12.250290556304341,
 0.015583927843016866,
 4,
 array([[  24.00521739,   53.17043478,   51.82434783],
        [ 604.22434783, 1338.32869565, 1304.44695652],
        [  13.77043478,   30.50086957,   29.72869565]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          1         0
4         0          1         0

Sex_Right_Time   No  Unsure   Yes
Negative
0               630    1371  1349
1                23      63    43

Chi2 value= 3.4427705677909675
p-value= 0.17881826219625105
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
No change
0                47     117    68
1               606    1317  1324

Chi2 value= 12.52594554771527
p-value= 0.0019055725319374467
Degrees of freedom= 2

Sex_Right_Time   No  Unsure   Yes
Positive
0               640    1392  1373
1                13      42    19

Chi2 value= 8.370362372464058
p-value= 0.015219448137623404
Degrees of freedom= 2

Contraception       No  Yes
Height Direction
Negative           935  126
No change          499   54
Positive          1635  265

(7.628112010561327,
 0.02205852776199636,
 2,
 array([[ 926.63887308,  134.36112692],
        [ 482.97011952,   70.02988048],
        [1659.3910074 ,  240.6089926 ]]))

   Negative  No change  Positive
0         0          1         0
1         0          0         1
2         0          0         1
3         0          0         1
4         0          0         1

Contraception    No  Yes
Negative
0              2134  319
1               935  126

Chi2 value= 0.7544058654006756
p-value= 0.3850848827477129
Degrees of freedom= 1

Contraception    No  Yes
No change
0              2570  391
1               499   54

Chi2 value= 4.679732834724243
p-value= 0.030520494729460296
Degrees of freedom= 1

Contraception    No  Yes
Positive
0              1434  180
1              1635  265

Chi2 value= 5.9137119443224435
p-value= 0.015023483011609731
Degrees of freedom= 1

Contraception       No  Yes
Weight Direction
Negative          1552  270
No change          302   26
Positive          1215  149

(18.039735343424518,
 0.0001209821345383218,
 2,
 array([[1591.26863973,  230.73136027],
        [ 286.4632897 ,   41.5367103 ],
        [1191.26807057,  172.73192943]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          0         1
4         0          0         1

Contraception    No  Yes
Negative
0              1517  175
1              1552  270

Chi2 value= 15.490333468340653
p-value= 8.292826365932852e-05
Degrees of freedom= 1

Contraception    No  Yes
No change
0              2767  419
1               302   26

Chi2 value= 6.8743940391475356
p-value= 0.008743939931907193
Degrees of freedom= 1

Contraception    No  Yes
Positive
0              1854  296
1              1215  149

Chi2 value= 5.847444402651633
p-value= 0.015599689218575642
Degrees of freedom= 1

Contraception        No  Yes
Smoking Direction
Negative            288   53
No change          2677  385
Positive            104    7

(6.634046825698739,
 0.03626060412586041,
 2,
 array([[ 297.81701764,   43.18298236],
        [2674.23961298,  387.76038702],
        [  96.94336938,   14.05663062]]))

   Negative  No change  Positive
0         0          1         0
1         1          0         0
2         0          1         0
3         0          1         0
4         0          0         1

Contraception    No  Yes
Negative
0              2781  392
1               288   53

Chi2 value= 2.549046493038554
p-value= 0.11036084118168088
Degrees of freedom= 1

Contraception    No  Yes
No change
0               392   60
1              2677  385

Chi2 value= 0.11729253204000656
p-value= 0.7319897128563178
Degrees of freedom= 1

Contraception    No  Yes
Positive
0              2965  438
1               104    7

Chi2 value= 3.615970505267277
p-value= 0.05722732285660212
Degrees of freedom= 1

Contraception        No  Yes
Alcohol Direction
Negative            448   94
No change          2358  302
Positive            263   49

(17.46982683172405,
 0.00016087008955635934,
 2,
 array([[ 473.36311895,   68.63688105],
        [2323.14741036,  336.85258964],
        [ 272.48947069,   39.51052931]]))

   Negative  No change  Positive
0         0          1         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Contraception    No  Yes
Negative
0              2621  351
1               448   94

Chi2 value= 12.193025890721128
p-value= 0.000479685113510421
Degrees of freedom= 1

Contraception    No  Yes
No change
0               711  143
1              2358  302

Chi2 value= 16.50546742729617
p-value= 4.850998900412995e-05
Degrees of freedom= 1

Contraception    No  Yes
Positive
0              2806  396
1               263   49

Chi2 value= 2.570044788046352
p-value= 0.10890464847171906
Degrees of freedom= 1

Contraception         No  Yes
Conceive Direction
Negative              98   43
No change           2816  380
Positive              47   15

(48.8407756883375,
 2.4794783089793465e-11,
 2,
 array([[ 122.83053839,   18.16946161],
        [2784.15887026,  411.84112974],
        [  54.01059135,    7.98940865]]))

   Negative  No change  Positive
0         0          0         0
1         1          0         0
2         0          0         0
3         0          0         0
4         0          1         0

Contraception    No  Yes
Negative
0              2971  402
1                98   43

Chi2 value= 40.573753645286
p-value= 1.8933282595008342e-10
Degrees of freedom= 1

Contraception    No  Yes
No change
0               253   65
1              2816  380

Chi2 value= 18.353076038556587
p-value= 1.8352244727479197e-05
Degrees of freedom= 1

Contraception    No  Yes
Positive
0              3022  430
1                47   15

Chi2 value= 6.562050966475381
p-value= 0.01041762299933205
Degrees of freedom= 1

Contraception      No  Yes
Month Direction
Negative          371   17
No change        2524  420
Positive          174    8

(42.150378640586325,
 7.033339366764042e-10,
 2,
 array([[ 338.86511098,   49.13488902],
        [2571.18269778,  372.81730222],
        [ 158.95219124,   23.04780876]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          1         0
3         0          1         0
4         0          1         0

Contraception    No  Yes
Negative
0              2698  428
1               371   17

Chi2 value= 26.215630253899786
p-value= 3.053410706024166e-07
Degrees of freedom= 1

Contraception    No  Yes
No change
0               545   25
1              2524  420

Chi2 value= 41.26174610910374
p-value= 1.3314931305892887e-10
Degrees of freedom= 1

Contraception    No  Yes
Positive
0              2895  437
1               174    8

Chi2 value= 11.088355936066103
p-value= 0.0008687146740345631
Degrees of freedom= 1

Contraception                      No  Yes
Menstrual_Information Direction
Negative                           71   22
No change                        2624  369
Positive                           39    8

(11.201862709419522,
 0.0036944212970001634,
 2,
 array([[  81.15608043,   11.84391957],
        [2611.82955634,  381.17044366],
        [  41.01436323,    5.98563677]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          0         0
4         0          1         0

Contraception    No  Yes
Negative
0              2998  423
1                71   22

Chi2 value= 9.440545899707045
p-value= 0.00212240311219425
Degrees of freedom= 1

Contraception    No  Yes
No change
0               445   76
1              2624  369

Chi2 value= 1.8475840627005196
p-value= 0.17406464381123576
Degrees of freedom= 1

Contraception    No  Yes
Positive
0              3030  437
1                39    8

Chi2 value= 0.467294809980866
p-value= 0.4942343219296699
Degrees of freedom= 1

Contraception              No  Yes
Contraception Direction
Negative                    0  131
No change                2993  314
Positive                   76    0

(944.4990362960383,
 8.028606761669e-206,
 2,
 array([[ 114.41064314,   16.58935686],
        [2888.21371656,  418.78628344],
        [  66.3756403 ,    9.6243597 ]]))

   Negative  No change  Positive
0         0          0         0
1         0          1         0
2         0          0         0
3         0          1         0
4         0          1         0

Contraception    No  Yes
Negative
0              3069  314
1                 0  131

Chi2 value= 930.2585845179519
p-value= 2.594702756235186e-204
Degrees of freedom= 1

Contraception    No  Yes
No change
0                76  131
1              2993  314

Chi2 value= 504.775435701348
p-value= 8.688436693159103e-112
Degrees of freedom= 1

Contraception    No  Yes
Positive
0              2993  445
1                76    0

Chi2 value= 10.1235703031874
p-value= 0.0014638516269104725
Degrees of freedom= 1

In [ ]:
dfProfileFirst_DiffSecond.Trying_Conceive
,dfProfileFirst_DiffSecond['Previous_Children']
                         ,dfProfileFirst_DiffSecond['STI_Tested'],
                         dfProfileFirst_DiffSecond['STI_Positive'],dfProfileFirst_DiffSecond['Menstrual_Information'],
                         dfProfileFirst_DiffSecond['Sex_Right_Time'],dfProfileFirst_DiffSecond['Contraception']
                         
                         dfProfileFirst_DiffSecond['Age Direction'],dfProfileFirst_DiffSecond['Height Direction'],
                         dfProfileFirst_DiffSecond['Weight Direction'],dfProfileFirst_DiffSecond['Smoking Direction'],
                         dfProfileFirst_DiffSecond['Alcohol Direction'],dfProfileFirst_DiffSecond['Conceive Direction'],
                         dfProfileFirst_DiffSecond['Month Direction'],dfProfileFirst_DiffSecond['Children Direction'],
                         dfProfileFirst_DiffSecond['STI Direction'],dfProfileFirst_DiffSecond['STI Positive Direction'],
                         dfProfileFirst_DiffSecond['Menstrual_Information Direction'],dfProfileFirst_DiffSecond['Sex_Frequency Direction'],
                         dfProfileFirst_DiffSecond['Sex_Right_Time Direction'],dfProfileFirst_DiffSecond['Contraception Direction']

IndentationError: ignored